export type Emoji = {
  emoji: string;
  name: string;
  keywords: string[];
  category: string;
  unicode: string;
  skinTones?: string[];
};

export const emojiData: Emoji[] = [
  { emoji: "😀", name: "Grinning Face", keywords: ["smile", "happy"], category: "Smileys & People", unicode: "U+1F600" },
  { emoji: "😃", name: "Grinning Face with Big Eyes", keywords: ["smile", "happy", "joy"], category: "Smileys & People", unicode: "U+1F603" },
  { emoji: "😄", name: "Grinning Face with Smiling Eyes", keywords: ["smile", "happy", "joy"], category: "Smileys & People", unicode: "U+1F604" },
  { emoji: "😁", name: "Beaming Face with Smiling Eyes", keywords: ["smile", "happy"], category: "Smileys & People", unicode: "U+1F601" },
  { emoji: "😆", name: "Grinning Squinting Face", keywords: ["laugh", "happy"], category: "Smileys & People", unicode: "U+1F606" },
  { emoji: "😅", name: "Grinning Face with Sweat", keywords: ["smile", "sweat"], category: "Smileys & People", unicode: "U+1F605" },
  { emoji: "🤣", name: "Rolling on the Floor Laughing", keywords: ["laugh", "lol"], category: "Smileys & People", unicode: "U+1F923" },
  { emoji: "😂", name: "Face with Tears of Joy", keywords: ["laugh", "cry", "lol"], category: "Smileys & People", unicode: "U+1F602" },
  { emoji: "🙂", name: "Slightly Smiling Face", keywords: ["smile"], category: "Smileys & People", unicode: "U+1F642" },
  { emoji: "😉", name: "Winking Face", keywords: ["wink", "flirt"], category: "Smileys & People", unicode: "U+1F609" },
  { emoji: "😊", name: "Smiling Face with Smiling Eyes", keywords: ["smile", "blush"], category: "Smileys & People", unicode: "U+1F60A" },
  { emoji: "😇", name: "Smiling Face with Halo", keywords: ["angel", "innocent"], category: "Smileys & People", unicode: "U+1F607" },
  { emoji: "🥰", name: "Smiling Face with Hearts", keywords: ["love", "crush"], category: "Smileys & People", unicode: "U+1F970" },
  { emoji: "😍", name: "Smiling Face with Heart-Eyes", keywords: ["love", "crush"], category: "Smileys & People", unicode: "U+1F60D" },
  { emoji: "🤩", name: "Star-Struck", keywords: ["eyes", "star"], category: "Smileys & People", unicode: "U+1F929" },
  { emoji: "😘", name: "Face Blowing a Kiss", keywords: ["kiss", "love"], category: "Smileys & People", unicode: "U+1F618" },
  { emoji: "😗", name: "Kissing Face", keywords: ["kiss"], category: "Smileys & People", unicode: "U+1F617" },
  { emoji: "😚", name: "Kissing Face with Closed Eyes", keywords: ["kiss"], category: "Smileys & People", unicode: "U+1F61A" },
  { emoji: "😙", name: "Kissing Face with Smiling Eyes", keywords: ["kiss"], category: "Smileys & People", unicode: "U+1F619" },
  { emoji: "😋", name: "Face Savoring Food", keywords: ["yum", "delicious"], category: "Smileys & People", unicode: "U+1F60B" },
  { emoji: "😛", name: "Face with Tongue", keywords: ["tongue"], category: "Smileys & People", unicode: "U+1F61B" },
  { emoji: "😜", name: "Winking Face with Tongue", keywords: ["wink", "tongue"], category: "Smileys & People", unicode: "U+1F61C" },
  { emoji: "🤪", name: "Zany Face", keywords: ["crazy", "wild"], category: "Smileys & People", unicode: "U+1F92A" },
  { emoji: "😝", name: "Squinting Face with Tongue", keywords: ["tongue"], category: "Smileys & People", unicode: "U+1F61D" },
  { emoji: "🤑", name: "Money-Mouth Face", keywords: ["money", "rich"], category: "Smileys & People", unicode: "U+1F911" },
  { emoji: "🤗", name: "Hugging Face", keywords: ["hug"], category: "Smileys & People", unicode: "U+1F917" },
  { emoji: "🤭", name: "Face with Hand Over Mouth", keywords: ["oops", "secret"], category: "Smileys & People", unicode: "U+1F92D" },
  { emoji: "🤫", name: "Shushing Face", keywords: ["quiet", "shh"], category: "Smileys & People", unicode: "U+1F92B" },
  { emoji: "🤔", name: "Thinking Face", keywords: ["think", "hmm"], category: "Smileys & People", unicode: "U+1F914" },
  { emoji: "😐", name: "Neutral Face", keywords: ["neutral", "meh"], category: "Smileys & People", unicode: "U+1F610" },
  { emoji: "😑", name: "Expressionless Face", keywords: ["blank", "meh"], category: "Smileys & People", unicode: "U+1F611" },
  { emoji: "😶", name: "Face Without Mouth", keywords: ["silent"], category: "Smileys & People", unicode: "U+1F636" },
  { emoji: "😏", name: "Smirking Face", keywords: ["smirk"], category: "Smileys & People", unicode: "U+1F60F" },
  { emoji: "😒", name: "Unamused Face", keywords: ["annoyed"], category: "Smileys & People", unicode: "U+1F612" },
  { emoji: "🙄", name: "Face with Rolling Eyes", keywords: ["eyeroll"], category: "Smileys & People", unicode: "U+1F644" },
  { emoji: "😬", name: "Grimacing Face", keywords: ["awkward"], category: "Smileys & People", unicode: "U+1F62C" },
  { emoji: "😌", name: "Relieved Face", keywords: ["calm", "relief"], category: "Smileys & People", unicode: "U+1F60C" },
  { emoji: "😔", name: "Pensive Face", keywords: ["sad", "thoughtful"], category: "Smileys & People", unicode: "U+1F614" },
  { emoji: "😪", name: "Sleepy Face", keywords: ["tired", "sleep"], category: "Smileys & People", unicode: "U+1F62A" },
  { emoji: "🤤", name: "Drooling Face", keywords: ["drool"], category: "Smileys & People", unicode: "U+1F924" },
  { emoji: "😴", name: "Sleeping Face", keywords: ["sleep", "zzz"], category: "Smileys & People", unicode: "U+1F634" },
  { emoji: "😷", name: "Face with Medical Mask", keywords: ["sick", "mask"], category: "Smileys & People", unicode: "U+1F637" },
  { emoji: "🤒", name: "Face with Thermometer", keywords: ["sick", "ill"], category: "Smileys & People", unicode: "U+1F912" },
  { emoji: "🤕", name: "Face with Head-Bandage", keywords: ["hurt", "injured"], category: "Smileys & People", unicode: "U+1F915" },
  { emoji: "🤢", name: "Nauseated Face", keywords: ["sick", "gross"], category: "Smileys & People", unicode: "U+1F922" },
  { emoji: "🤮", name: "Face Vomiting", keywords: ["sick", "puke"], category: "Smileys & People", unicode: "U+1F92E" },
  { emoji: "🤧", name: "Sneezing Face", keywords: ["sneeze", "sick"], category: "Smileys & People", unicode: "U+1F927" },
  { emoji: "🥵", name: "Hot Face", keywords: ["hot", "heat"], category: "Smileys & People", unicode: "U+1F975" },
  { emoji: "🥶", name: "Cold Face", keywords: ["cold", "freeze"], category: "Smileys & People", unicode: "U+1F976" },
  { emoji: "😎", name: "Smiling Face with Sunglasses", keywords: ["cool", "sunglasses"], category: "Smileys & People", unicode: "U+1F60E" },
  { emoji: "🤓", name: "Nerd Face", keywords: ["nerd", "geek"], category: "Smileys & People", unicode: "U+1F913" },
  { emoji: "🧐", name: "Face with Monocle", keywords: ["detective"], category: "Smileys & People", unicode: "U+1F9D0" },
  { emoji: "😕", name: "Confused Face", keywords: ["confused"], category: "Smileys & People", unicode: "U+1F615" },
  { emoji: "😟", name: "Worried Face", keywords: ["worried", "concerned"], category: "Smileys & People", unicode: "U+1F61F" },
  { emoji: "🙁", name: "Slightly Frowning Face", keywords: ["sad"], category: "Smileys & People", unicode: "U+1F641" },
  { emoji: "☹️", name: "Frowning Face", keywords: ["sad"], category: "Smileys & People", unicode: "U+2639" },
  { emoji: "😮", name: "Face with Open Mouth", keywords: ["wow", "surprised"], category: "Smileys & People", unicode: "U+1F62E" },
  { emoji: "😯", name: "Hushed Face", keywords: ["surprised"], category: "Smileys & People", unicode: "U+1F62F" },
  { emoji: "😲", name: "Astonished Face", keywords: ["shocked"], category: "Smileys & People", unicode: "U+1F632" },
  { emoji: "😳", name: "Flushed Face", keywords: ["blush", "embarrassed"], category: "Smileys & People", unicode: "U+1F633" },
  { emoji: "🥺", name: "Pleading Face", keywords: ["puppy eyes", "beg"], category: "Smileys & People", unicode: "U+1F97A" },
  { emoji: "😦", name: "Frowning Face with Open Mouth", keywords: ["concerned"], category: "Smileys & People", unicode: "U+1F626" },
  { emoji: "😧", name: "Anguished Face", keywords: ["worried"], category: "Smileys & People", unicode: "U+1F627" },
  { emoji: "😨", name: "Fearful Face", keywords: ["scared", "fear"], category: "Smileys & People", unicode: "U+1F628" },
  { emoji: "😰", name: "Anxious Face with Sweat", keywords: ["nervous", "anxious"], category: "Smileys & People", unicode: "U+1F630" },
  { emoji: "😥", name: "Sad but Relieved Face", keywords: ["sad", "relief"], category: "Smileys & People", unicode: "U+1F625" },
  { emoji: "😢", name: "Crying Face", keywords: ["cry", "sad", "tear"], category: "Smileys & People", unicode: "U+1F622" },
  { emoji: "😭", name: "Loudly Crying Face", keywords: ["cry", "sob"], category: "Smileys & People", unicode: "U+1F62D" },
  { emoji: "😱", name: "Face Screaming in Fear", keywords: ["scream", "scared"], category: "Smileys & People", unicode: "U+1F631" },
  { emoji: "😖", name: "Confounded Face", keywords: ["frustrated"], category: "Smileys & People", unicode: "U+1F616" },
  { emoji: "😣", name: "Persevering Face", keywords: ["struggle"], category: "Smileys & People", unicode: "U+1F623" },
  { emoji: "😞", name: "Disappointed Face", keywords: ["sad", "disappointed"], category: "Smileys & People", unicode: "U+1F61E" },
  { emoji: "😓", name: "Downcast Face with Sweat", keywords: ["sad", "sweat"], category: "Smileys & People", unicode: "U+1F613" },
  { emoji: "😩", name: "Weary Face", keywords: ["tired", "exhausted"], category: "Smileys & People", unicode: "U+1F629" },
  { emoji: "😫", name: "Tired Face", keywords: ["tired", "exhausted"], category: "Smileys & People", unicode: "U+1F62B" },
  { emoji: "🥱", name: "Yawning Face", keywords: ["yawn", "tired"], category: "Smileys & People", unicode: "U+1F971" },
  { emoji: "😤", name: "Face with Steam From Nose", keywords: ["angry", "frustrated"], category: "Smileys & People", unicode: "U+1F624" },
  { emoji: "😡", name: "Pouting Face", keywords: ["angry", "mad"], category: "Smileys & People", unicode: "U+1F621" },
  { emoji: "😠", name: "Angry Face", keywords: ["angry", "mad"], category: "Smileys & People", unicode: "U+1F620" },
  { emoji: "🤬", name: "Face with Symbols on Mouth", keywords: ["curse", "swear"], category: "Smileys & People", unicode: "U+1F92C" },
  { emoji: "👋", name: "Waving Hand", keywords: ["hello", "hi", "bye"], category: "Smileys & People", unicode: "U+1F44B", skinTones: ["👋🏻", "👋🏼", "👋🏽", "👋🏾", "👋🏿"] },
  { emoji: "🤚", name: "Raised Back of Hand", keywords: ["hand"], category: "Smileys & People", unicode: "U+1F91A", skinTones: ["🤚🏻", "🤚🏼", "🤚🏽", "🤚🏾", "🤚🏿"] },
  { emoji: "✋", name: "Raised Hand", keywords: ["hand", "stop"], category: "Smileys & People", unicode: "U+270B", skinTones: ["✋🏻", "✋🏼", "✋🏽", "✋🏾", "✋🏿"] },
  { emoji: "👌", name: "OK Hand", keywords: ["ok", "okay"], category: "Smileys & People", unicode: "U+1F44C", skinTones: ["👌🏻", "👌🏼", "👌🏽", "👌🏾", "👌🏿"] },
  { emoji: "✌️", name: "Victory Hand", keywords: ["peace", "victory"], category: "Smileys & People", unicode: "U+270C", skinTones: ["✌🏻", "✌🏼", "✌🏽", "✌🏾", "✌🏿"] },
  { emoji: "🤞", name: "Crossed Fingers", keywords: ["luck", "hope"], category: "Smileys & People", unicode: "U+1F91E", skinTones: ["🤞🏻", "🤞🏼", "🤞🏽", "🤞🏾", "🤞🏿"] },
  { emoji: "🤟", name: "Love-You Gesture", keywords: ["love", "you"], category: "Smileys & People", unicode: "U+1F91F", skinTones: ["🤟🏻", "🤟🏼", "🤟🏽", "🤟🏾", "🤟🏿"] },
  { emoji: "🤘", name: "Sign of the Horns", keywords: ["rock", "metal"], category: "Smileys & People", unicode: "U+1F918", skinTones: ["🤘🏻", "🤘🏼", "🤘🏽", "🤘🏾", "🤘🏿"] },
  { emoji: "👍", name: "Thumbs Up", keywords: ["like", "yes"], category: "Smileys & People", unicode: "U+1F44D", skinTones: ["👍🏻", "👍🏼", "👍🏽", "👍🏾", "👍🏿"] },
  { emoji: "👎", name: "Thumbs Down", keywords: ["dislike", "no"], category: "Smileys & People", unicode: "U+1F44E", skinTones: ["👎🏻", "👎🏼", "👎🏽", "👎🏾", "👎🏿"] },
  { emoji: "✊", name: "Raised Fist", keywords: ["fist", "power"], category: "Smileys & People", unicode: "U+270A", skinTones: ["✊🏻", "✊🏼", "✊🏽", "✊🏾", "✊🏿"] },
  { emoji: "👊", name: "Oncoming Fist", keywords: ["fist", "punch"], category: "Smileys & People", unicode: "U+1F44A", skinTones: ["👊🏻", "👊🏼", "👊🏽", "👊🏾", "👊🏿"] },
  { emoji: "👏", name: "Clapping Hands", keywords: ["clap", "applause"], category: "Smileys & People", unicode: "U+1F44F", skinTones: ["👏🏻", "👏🏼", "👏🏽", "👏🏾", "👏🏿"] },
  { emoji: "🙌", name: "Raising Hands", keywords: ["celebrate", "yay"], category: "Smileys & People", unicode: "U+1F64C", skinTones: ["🙌🏻", "🙌🏼", "🙌🏽", "🙌🏾", "🙌🏿"] },
  { emoji: "🙏", name: "Folded Hands", keywords: ["pray", "thanks"], category: "Smileys & People", unicode: "U+1F64F", skinTones: ["🙏🏻", "🙏🏼", "🙏🏽", "🙏🏾", "🙏🏿"] },
  { emoji: "💪", name: "Flexed Biceps", keywords: ["strong", "muscle"], category: "Smileys & People", unicode: "U+1F4AA", skinTones: ["💪🏻", "💪🏼", "💪🏽", "💪🏾", "💪🏿"] },

  // Animals & Nature
  { emoji: "🐶", name: "Dog Face", keywords: ["dog", "puppy", "pet"], category: "Animals & Nature", unicode: "U+1F436" },
  { emoji: "🐱", name: "Cat Face", keywords: ["cat", "kitten", "pet"], category: "Animals & Nature", unicode: "U+1F431" },
  { emoji: "🐭", name: "Mouse Face", keywords: ["mouse"], category: "Animals & Nature", unicode: "U+1F42D" },
  { emoji: "🐹", name: "Hamster", keywords: ["hamster", "pet"], category: "Animals & Nature", unicode: "U+1F439" },
  { emoji: "🐰", name: "Rabbit Face", keywords: ["rabbit", "bunny"], category: "Animals & Nature", unicode: "U+1F430" },
  { emoji: "🦊", name: "Fox", keywords: ["fox"], category: "Animals & Nature", unicode: "U+1F98A" },
  { emoji: "🐻", name: "Bear", keywords: ["bear"], category: "Animals & Nature", unicode: "U+1F43B" },
  { emoji: "🐼", name: "Panda", keywords: ["panda"], category: "Animals & Nature", unicode: "U+1F43C" },
  { emoji: "🐨", name: "Koala", keywords: ["koala"], category: "Animals & Nature", unicode: "U+1F428" },
  { emoji: "🐯", name: "Tiger Face", keywords: ["tiger"], category: "Animals & Nature", unicode: "U+1F42F" },
  { emoji: "🦁", name: "Lion", keywords: ["lion"], category: "Animals & Nature", unicode: "U+1F981" },
  { emoji: "🐮", name: "Cow Face", keywords: ["cow"], category: "Animals & Nature", unicode: "U+1F42E" },
  { emoji: "🐷", name: "Pig Face", keywords: ["pig"], category: "Animals & Nature", unicode: "U+1F437" },
  { emoji: "🐸", name: "Frog", keywords: ["frog"], category: "Animals & Nature", unicode: "U+1F438" },
  { emoji: "🐵", name: "Monkey Face", keywords: ["monkey"], category: "Animals & Nature", unicode: "U+1F435" },
  { emoji: "🙈", name: "See-No-Evil Monkey", keywords: ["monkey", "eyes"], category: "Animals & Nature", unicode: "U+1F648" },
  { emoji: "🙉", name: "Hear-No-Evil Monkey", keywords: ["monkey", "ears"], category: "Animals & Nature", unicode: "U+1F649" },
  { emoji: "🙊", name: "Speak-No-Evil Monkey", keywords: ["monkey", "mouth"], category: "Animals & Nature", unicode: "U+1F64A" },
  { emoji: "🐔", name: "Chicken", keywords: ["chicken", "hen"], category: "Animals & Nature", unicode: "U+1F414" },
  { emoji: "🐧", name: "Penguin", keywords: ["penguin"], category: "Animals & Nature", unicode: "U+1F427" },
  { emoji: "🐦", name: "Bird", keywords: ["bird"], category: "Animals & Nature", unicode: "U+1F426" },
  { emoji: "🐤", name: "Baby Chick", keywords: ["chick", "baby"], category: "Animals & Nature", unicode: "U+1F424" },
  { emoji: "🦆", name: "Duck", keywords: ["duck"], category: "Animals & Nature", unicode: "U+1F986" },
  { emoji: "🦅", name: "Eagle", keywords: ["eagle", "bird"], category: "Animals & Nature", unicode: "U+1F985" },
  { emoji: "🦉", name: "Owl", keywords: ["owl"], category: "Animals & Nature", unicode: "U+1F989" },
  { emoji: "🦇", name: "Bat", keywords: ["bat"], category: "Animals & Nature", unicode: "U+1F987" },
  { emoji: "🐺", name: "Wolf", keywords: ["wolf"], category: "Animals & Nature", unicode: "U+1F43A" },
  { emoji: "🐗", name: "Boar", keywords: ["boar", "pig"], category: "Animals & Nature", unicode: "U+1F417" },
  { emoji: "🐴", name: "Horse Face", keywords: ["horse"], category: "Animals & Nature", unicode: "U+1F434" },
  { emoji: "🦄", name: "Unicorn", keywords: ["unicorn"], category: "Animals & Nature", unicode: "U+1F984" },
  { emoji: "🐝", name: "Honeybee", keywords: ["bee", "honey"], category: "Animals & Nature", unicode: "U+1F41D" },
  { emoji: "🐛", name: "Bug", keywords: ["bug", "insect"], category: "Animals & Nature", unicode: "U+1F41B" },
  { emoji: "🦋", name: "Butterfly", keywords: ["butterfly"], category: "Animals & Nature", unicode: "U+1F98B" },
  { emoji: "🐌", name: "Snail", keywords: ["snail", "slow"], category: "Animals & Nature", unicode: "U+1F40C" },
  { emoji: "🐞", name: "Lady Beetle", keywords: ["ladybug", "bug"], category: "Animals & Nature", unicode: "U+1F41E" },
  { emoji: "🐜", name: "Ant", keywords: ["ant", "bug"], category: "Animals & Nature", unicode: "U+1F41C" },
  { emoji: "🕷️", name: "Spider", keywords: ["spider"], category: "Animals & Nature", unicode: "U+1F577" },
  { emoji: "🦂", name: "Scorpion", keywords: ["scorpion"], category: "Animals & Nature", unicode: "U+1F982" },
  { emoji: "🐢", name: "Turtle", keywords: ["turtle", "slow"], category: "Animals & Nature", unicode: "U+1F422" },
  { emoji: "🐍", name: "Snake", keywords: ["snake"], category: "Animals & Nature", unicode: "U+1F40D" },
  { emoji: "🦎", name: "Lizard", keywords: ["lizard"], category: "Animals & Nature", unicode: "U+1F98E" },
  { emoji: "🦖", name: "T-Rex", keywords: ["dinosaur", "trex"], category: "Animals & Nature", unicode: "U+1F996" },
  { emoji: "🦕", name: "Sauropod", keywords: ["dinosaur"], category: "Animals & Nature", unicode: "U+1F995" },
  { emoji: "🐙", name: "Octopus", keywords: ["octopus"], category: "Animals & Nature", unicode: "U+1F419" },
  { emoji: "🦑", name: "Squid", keywords: ["squid"], category: "Animals & Nature", unicode: "U+1F991" },
  { emoji: "🦐", name: "Shrimp", keywords: ["shrimp"], category: "Animals & Nature", unicode: "U+1F990" },
  { emoji: "🦞", name: "Lobster", keywords: ["lobster"], category: "Animals & Nature", unicode: "U+1F99E" },
  { emoji: "🦀", name: "Crab", keywords: ["crab"], category: "Animals & Nature", unicode: "U+1F980" },
  { emoji: "🐡", name: "Blowfish", keywords: ["fish", "pufferfish"], category: "Animals & Nature", unicode: "U+1F421" },
  { emoji: "🐠", name: "Tropical Fish", keywords: ["fish"], category: "Animals & Nature", unicode: "U+1F420" },
  { emoji: "🐟", name: "Fish", keywords: ["fish"], category: "Animals & Nature", unicode: "U+1F41F" },
  { emoji: "🐬", name: "Dolphin", keywords: ["dolphin"], category: "Animals & Nature", unicode: "U+1F42C" },
  { emoji: "🐳", name: "Spouting Whale", keywords: ["whale"], category: "Animals & Nature", unicode: "U+1F433" },
  { emoji: "🐋", name: "Whale", keywords: ["whale"], category: "Animals & Nature", unicode: "U+1F40B" },
  { emoji: "🦈", name: "Shark", keywords: ["shark"], category: "Animals & Nature", unicode: "U+1F988" },
  { emoji: "🐊", name: "Crocodile", keywords: ["crocodile", "alligator"], category: "Animals & Nature", unicode: "U+1F40A" },
  { emoji: "🐅", name: "Tiger", keywords: ["tiger"], category: "Animals & Nature", unicode: "U+1F405" },
  { emoji: "🐆", name: "Leopard", keywords: ["leopard"], category: "Animals & Nature", unicode: "U+1F406" },
  { emoji: "🦓", name: "Zebra", keywords: ["zebra"], category: "Animals & Nature", unicode: "U+1F993" },
  { emoji: "🦍", name: "Gorilla", keywords: ["gorilla"], category: "Animals & Nature", unicode: "U+1F98D" },
  { emoji: "🦧", name: "Orangutan", keywords: ["orangutan", "ape"], category: "Animals & Nature", unicode: "U+1F9A7" },
  { emoji: "🐘", name: "Elephant", keywords: ["elephant"], category: "Animals & Nature", unicode: "U+1F418" },
  { emoji: "🦛", name: "Hippopotamus", keywords: ["hippo"], category: "Animals & Nature", unicode: "U+1F99B" },
  { emoji: "🦏", name: "Rhinoceros", keywords: ["rhino"], category: "Animals & Nature", unicode: "U+1F98F" },
  { emoji: "🐪", name: "Camel", keywords: ["camel"], category: "Animals & Nature", unicode: "U+1F42A" },
  { emoji: "🐫", name: "Two-Hump Camel", keywords: ["camel"], category: "Animals & Nature", unicode: "U+1F42B" },
  { emoji: "🦒", name: "Giraffe", keywords: ["giraffe"], category: "Animals & Nature", unicode: "U+1F992" },
  { emoji: "🦘", name: "Kangaroo", keywords: ["kangaroo"], category: "Animals & Nature", unicode: "U+1F998" },
  { emoji: "🐃", name: "Water Buffalo", keywords: ["buffalo"], category: "Animals & Nature", unicode: "U+1F403" },
  { emoji: "🐂", name: "Ox", keywords: ["ox"], category: "Animals & Nature", unicode: "U+1F402" },
  { emoji: "🐄", name: "Cow", keywords: ["cow"], category: "Animals & Nature", unicode: "U+1F404" },
  { emoji: "🐎", name: "Horse", keywords: ["horse"], category: "Animals & Nature", unicode: "U+1F40E" },
  { emoji: "🐖", name: "Pig", keywords: ["pig"], category: "Animals & Nature", unicode: "U+1F416" },
  { emoji: "🐏", name: "Ram", keywords: ["ram", "sheep"], category: "Animals & Nature", unicode: "U+1F40F" },
  { emoji: "🐑", name: "Ewe", keywords: ["sheep"], category: "Animals & Nature", unicode: "U+1F411" },
  { emoji: "🐐", name: "Goat", keywords: ["goat"], category: "Animals & Nature", unicode: "U+1F410" },
  { emoji: "🦌", name: "Deer", keywords: ["deer"], category: "Animals & Nature", unicode: "U+1F98C" },
  { emoji: "🐕", name: "Dog", keywords: ["dog"], category: "Animals & Nature", unicode: "U+1F415" },
  { emoji: "🐩", name: "Poodle", keywords: ["poodle", "dog"], category: "Animals & Nature", unicode: "U+1F429" },
  { emoji: "🐈", name: "Cat", keywords: ["cat"], category: "Animals & Nature", unicode: "U+1F408" },
  { emoji: "🐓", name: "Rooster", keywords: ["rooster", "chicken"], category: "Animals & Nature", unicode: "U+1F413" },
  { emoji: "🦃", name: "Turkey", keywords: ["turkey", "bird"], category: "Animals & Nature", unicode: "U+1F983" },
  { emoji: "🦚", name: "Peacock", keywords: ["peacock"], category: "Animals & Nature", unicode: "U+1F99A" },
  { emoji: "🦜", name: "Parrot", keywords: ["parrot"], category: "Animals & Nature", unicode: "U+1F99C" },
  { emoji: "🦢", name: "Swan", keywords: ["swan"], category: "Animals & Nature", unicode: "U+1F9A2" },
  { emoji: "🕊️", name: "Dove", keywords: ["dove", "peace"], category: "Animals & Nature", unicode: "U+1F54A" },
  { emoji: "🐇", name: "Rabbit", keywords: ["rabbit"], category: "Animals & Nature", unicode: "U+1F407" },
  { emoji: "🦝", name: "Raccoon", keywords: ["raccoon"], category: "Animals & Nature", unicode: "U+1F99D" },
  { emoji: "🦨", name: "Skunk", keywords: ["skunk"], category: "Animals & Nature", unicode: "U+1F9A8" },
  { emoji: "🦡", name: "Badger", keywords: ["badger"], category: "Animals & Nature", unicode: "U+1F9A1" },
  { emoji: "🦦", name: "Otter", keywords: ["otter"], category: "Animals & Nature", unicode: "U+1F9A6" },
  { emoji: "🦥", name: "Sloth", keywords: ["sloth"], category: "Animals & Nature", unicode: "U+1F9A5" },
  { emoji: "🐁", name: "Mouse", keywords: ["mouse"], category: "Animals & Nature", unicode: "U+1F401" },
  { emoji: "🐀", name: "Rat", keywords: ["rat"], category: "Animals & Nature", unicode: "U+1F400" },
  { emoji: "🐿️", name: "Chipmunk", keywords: ["chipmunk"], category: "Animals & Nature", unicode: "U+1F43F" },
  { emoji: "🦔", name: "Hedgehog", keywords: ["hedgehog"], category: "Animals & Nature", unicode: "U+1F994" },
  { emoji: "🌲", name: "Evergreen Tree", keywords: ["tree", "pine"], category: "Animals & Nature", unicode: "U+1F332" },
  { emoji: "🌳", name: "Deciduous Tree", keywords: ["tree"], category: "Animals & Nature", unicode: "U+1F333" },
  { emoji: "🌴", name: "Palm Tree", keywords: ["palm", "tree"], category: "Animals & Nature", unicode: "U+1F334" },
  { emoji: "🌵", name: "Cactus", keywords: ["cactus", "desert"], category: "Animals & Nature", unicode: "U+1F335" },
  { emoji: "🌱", name: "Seedling", keywords: ["plant", "growing"], category: "Animals & Nature", unicode: "U+1F331" },
  { emoji: "🌿", name: "Herb", keywords: ["herb", "plant"], category: "Animals & Nature", unicode: "U+1F33F" },
  { emoji: "☘️", name: "Shamrock", keywords: ["shamrock", "clover"], category: "Animals & Nature", unicode: "U+2618" },
  { emoji: "🍀", name: "Four Leaf Clover", keywords: ["clover", "luck"], category: "Animals & Nature", unicode: "U+1F340" },
  { emoji: "🌾", name: "Sheaf of Rice", keywords: ["rice", "plant"], category: "Animals & Nature", unicode: "U+1F33E" },
  { emoji: "🌺", name: "Hibiscus", keywords: ["flower"], category: "Animals & Nature", unicode: "U+1F33A" },
  { emoji: "🌻", name: "Sunflower", keywords: ["sunflower", "flower"], category: "Animals & Nature", unicode: "U+1F33B" },
  { emoji: "🌹", name: "Rose", keywords: ["rose", "flower"], category: "Animals & Nature", unicode: "U+1F339" },
  { emoji: "🥀", name: "Wilted Flower", keywords: ["flower", "wilted"], category: "Animals & Nature", unicode: "U+1F940" },
  { emoji: "🌷", name: "Tulip", keywords: ["tulip", "flower"], category: "Animals & Nature", unicode: "U+1F337" },
  { emoji: "🌸", name: "Cherry Blossom", keywords: ["blossom", "flower"], category: "Animals & Nature", unicode: "U+1F338" },
  { emoji: "💐", name: "Bouquet", keywords: ["bouquet", "flowers"], category: "Animals & Nature", unicode: "U+1F490" },
  { emoji: "🍄", name: "Mushroom", keywords: ["mushroom"], category: "Animals & Nature", unicode: "U+1F344" },
  { emoji: "🌰", name: "Chestnut", keywords: ["chestnut", "nut"], category: "Animals & Nature", unicode: "U+1F330" },

  // Food & Drink
  { emoji: "🍎", name: "Red Apple", keywords: ["apple", "fruit"], category: "Food & Drink", unicode: "U+1F34E" },
  { emoji: "🍐", name: "Pear", keywords: ["pear", "fruit"], category: "Food & Drink", unicode: "U+1F350" },
  { emoji: "🍊", name: "Tangerine", keywords: ["orange", "fruit"], category: "Food & Drink", unicode: "U+1F34A" },
  { emoji: "🍋", name: "Lemon", keywords: ["lemon", "fruit"], category: "Food & Drink", unicode: "U+1F34B" },
  { emoji: "🍌", name: "Banana", keywords: ["banana", "fruit"], category: "Food & Drink", unicode: "U+1F34C" },
  { emoji: "🍉", name: "Watermelon", keywords: ["watermelon", "fruit"], category: "Food & Drink", unicode: "U+1F349" },
  { emoji: "🍇", name: "Grapes", keywords: ["grapes", "fruit"], category: "Food & Drink", unicode: "U+1F347" },
  { emoji: "🍓", name: "Strawberry", keywords: ["strawberry", "fruit"], category: "Food & Drink", unicode: "U+1F353" },
  { emoji: "🍈", name: "Melon", keywords: ["melon", "fruit"], category: "Food & Drink", unicode: "U+1F348" },
  { emoji: "🍒", name: "Cherries", keywords: ["cherry", "fruit"], category: "Food & Drink", unicode: "U+1F352" },
  { emoji: "🍑", name: "Peach", keywords: ["peach", "fruit"], category: "Food & Drink", unicode: "U+1F351" },
  { emoji: "🥭", name: "Mango", keywords: ["mango", "fruit"], category: "Food & Drink", unicode: "U+1F96D" },
  { emoji: "🍍", name: "Pineapple", keywords: ["pineapple", "fruit"], category: "Food & Drink", unicode: "U+1F34D" },
  { emoji: "🥥", name: "Coconut", keywords: ["coconut", "fruit"], category: "Food & Drink", unicode: "U+1F965" },
  { emoji: "🥝", name: "Kiwi Fruit", keywords: ["kiwi", "fruit"], category: "Food & Drink", unicode: "U+1F95D" },
  { emoji: "🍅", name: "Tomato", keywords: ["tomato", "vegetable"], category: "Food & Drink", unicode: "U+1F345" },
  { emoji: "🍆", name: "Eggplant", keywords: ["eggplant", "vegetable"], category: "Food & Drink", unicode: "U+1F346" },
  { emoji: "🥑", name: "Avocado", keywords: ["avocado", "fruit"], category: "Food & Drink", unicode: "U+1F951" },
  { emoji: "🥦", name: "Broccoli", keywords: ["broccoli", "vegetable"], category: "Food & Drink", unicode: "U+1F966" },
  { emoji: "🥬", name: "Leafy Green", keywords: ["lettuce", "vegetable"], category: "Food & Drink", unicode: "U+1F96C" },
  { emoji: "🥒", name: "Cucumber", keywords: ["cucumber", "vegetable"], category: "Food & Drink", unicode: "U+1F952" },
  { emoji: "🌶️", name: "Hot Pepper", keywords: ["pepper", "hot", "spicy"], category: "Food & Drink", unicode: "U+1F336" },
  { emoji: "🌽", name: "Ear of Corn", keywords: ["corn", "vegetable"], category: "Food & Drink", unicode: "U+1F33D" },
  { emoji: "🥕", name: "Carrot", keywords: ["carrot", "vegetable"], category: "Food & Drink", unicode: "U+1F955" },
  { emoji: "🧄", name: "Garlic", keywords: ["garlic", "vegetable"], category: "Food & Drink", unicode: "U+1F9C4" },
  { emoji: "🧅", name: "Onion", keywords: ["onion", "vegetable"], category: "Food & Drink", unicode: "U+1F9C5" },
  { emoji: "🥔", name: "Potato", keywords: ["potato", "vegetable"], category: "Food & Drink", unicode: "U+1F954" },
  { emoji: "🍠", name: "Roasted Sweet Potato", keywords: ["sweet potato", "vegetable"], category: "Food & Drink", unicode: "U+1F360" },
  { emoji: "🥐", name: "Croissant", keywords: ["croissant", "bread"], category: "Food & Drink", unicode: "U+1F950" },
  { emoji: "🥯", name: "Bagel", keywords: ["bagel", "bread"], category: "Food & Drink", unicode: "U+1F96F" },
  { emoji: "🍞", name: "Bread", keywords: ["bread"], category: "Food & Drink", unicode: "U+1F35E" },
  { emoji: "🥖", name: "Baguette Bread", keywords: ["baguette", "bread"], category: "Food & Drink", unicode: "U+1F956" },
  { emoji: "🥨", name: "Pretzel", keywords: ["pretzel"], category: "Food & Drink", unicode: "U+1F968" },
  { emoji: "🧀", name: "Cheese Wedge", keywords: ["cheese"], category: "Food & Drink", unicode: "U+1F9C0" },
  { emoji: "🥚", name: "Egg", keywords: ["egg"], category: "Food & Drink", unicode: "U+1F95A" },
  { emoji: "🍳", name: "Cooking", keywords: ["egg", "cooking"], category: "Food & Drink", unicode: "U+1F373" },
  { emoji: "🥞", name: "Pancakes", keywords: ["pancakes", "breakfast"], category: "Food & Drink", unicode: "U+1F95E" },
  { emoji: "🧇", name: "Waffle", keywords: ["waffle", "breakfast"], category: "Food & Drink", unicode: "U+1F9C7" },
  { emoji: "🥓", name: "Bacon", keywords: ["bacon", "meat"], category: "Food & Drink", unicode: "U+1F953" },
  { emoji: "🥩", name: "Cut of Meat", keywords: ["meat", "steak"], category: "Food & Drink", unicode: "U+1F969" },
  { emoji: "🍗", name: "Poultry Leg", keywords: ["chicken", "meat"], category: "Food & Drink", unicode: "U+1F357" },
  { emoji: "🍖", name: "Meat on Bone", keywords: ["meat", "bone"], category: "Food & Drink", unicode: "U+1F356" },
  { emoji: "🌭", name: "Hot Dog", keywords: ["hotdog", "sausage"], category: "Food & Drink", unicode: "U+1F32D" },
  { emoji: "🍔", name: "Hamburger", keywords: ["burger", "hamburger"], category: "Food & Drink", unicode: "U+1F354" },
  { emoji: "🍟", name: "French Fries", keywords: ["fries", "chips"], category: "Food & Drink", unicode: "U+1F35F" },
  { emoji: "🍕", name: "Pizza", keywords: ["pizza"], category: "Food & Drink", unicode: "U+1F355" },
  { emoji: "🥪", name: "Sandwich", keywords: ["sandwich"], category: "Food & Drink", unicode: "U+1F96A" },
  { emoji: "🥙", name: "Stuffed Flatbread", keywords: ["pita", "falafel"], category: "Food & Drink", unicode: "U+1F959" },
  { emoji: "🧆", name: "Falafel", keywords: ["falafel"], category: "Food & Drink", unicode: "U+1F9C6" },
  { emoji: "🌮", name: "Taco", keywords: ["taco"], category: "Food & Drink", unicode: "U+1F32E" },
  { emoji: "🌯", name: "Burrito", keywords: ["burrito"], category: "Food & Drink", unicode: "U+1F32F" },
  { emoji: "🥗", name: "Green Salad", keywords: ["salad"], category: "Food & Drink", unicode: "U+1F957" },
  { emoji: "🥘", name: "Shallow Pan of Food", keywords: ["paella", "pan"], category: "Food & Drink", unicode: "U+1F958" },
  { emoji: "🍝", name: "Spaghetti", keywords: ["pasta", "spaghetti"], category: "Food & Drink", unicode: "U+1F35D" },
  { emoji: "🍜", name: "Steaming Bowl", keywords: ["noodles", "ramen"], category: "Food & Drink", unicode: "U+1F35C" },
  { emoji: "🍲", name: "Pot of Food", keywords: ["pot", "stew"], category: "Food & Drink", unicode: "U+1F372" },
  { emoji: "🍛", name: "Curry Rice", keywords: ["curry", "rice"], category: "Food & Drink", unicode: "U+1F35B" },
  { emoji: "🍣", name: "Sushi", keywords: ["sushi"], category: "Food & Drink", unicode: "U+1F363" },
  { emoji: "🍱", name: "Bento Box", keywords: ["bento", "lunch"], category: "Food & Drink", unicode: "U+1F371" },
  { emoji: "🥟", name: "Dumpling", keywords: ["dumpling"], category: "Food & Drink", unicode: "U+1F95F" },
  { emoji: "🍤", name: "Fried Shrimp", keywords: ["shrimp", "fried"], category: "Food & Drink", unicode: "U+1F364" },
  { emoji: "🍙", name: "Rice Ball", keywords: ["rice", "onigiri"], category: "Food & Drink", unicode: "U+1F359" },
  { emoji: "🍚", name: "Cooked Rice", keywords: ["rice"], category: "Food & Drink", unicode: "U+1F35A" },
  { emoji: "🍘", name: "Rice Cracker", keywords: ["rice", "cracker"], category: "Food & Drink", unicode: "U+1F358" },
  { emoji: "🍥", name: "Fish Cake with Swirl", keywords: ["fish cake"], category: "Food & Drink", unicode: "U+1F365" },
  { emoji: "🥠", name: "Fortune Cookie", keywords: ["cookie", "fortune"], category: "Food & Drink", unicode: "U+1F960" },
  { emoji: "🥮", name: "Moon Cake", keywords: ["cake", "moon"], category: "Food & Drink", unicode: "U+1F96E" },
  { emoji: "🍢", name: "Oden", keywords: ["oden", "skewer"], category: "Food & Drink", unicode: "U+1F362" },
  { emoji: "🍡", name: "Dango", keywords: ["dango", "dessert"], category: "Food & Drink", unicode: "U+1F361" },
  { emoji: "🍧", name: "Shaved Ice", keywords: ["ice", "dessert"], category: "Food & Drink", unicode: "U+1F367" },
  { emoji: "🍨", name: "Ice Cream", keywords: ["ice cream", "dessert"], category: "Food & Drink", unicode: "U+1F368" },
  { emoji: "🍦", name: "Soft Ice Cream", keywords: ["ice cream", "soft serve"], category: "Food & Drink", unicode: "U+1F366" },
  { emoji: "🥧", name: "Pie", keywords: ["pie"], category: "Food & Drink", unicode: "U+1F967" },
  { emoji: "🧁", name: "Cupcake", keywords: ["cupcake"], category: "Food & Drink", unicode: "U+1F9C1" },
  { emoji: "🍰", name: "Shortcake", keywords: ["cake", "dessert"], category: "Food & Drink", unicode: "U+1F370" },
  { emoji: "🎂", name: "Birthday Cake", keywords: ["cake", "birthday"], category: "Food & Drink", unicode: "U+1F382" },
  { emoji: "🍮", name: "Custard", keywords: ["custard", "pudding"], category: "Food & Drink", unicode: "U+1F36E" },
  { emoji: "🍭", name: "Lollipop", keywords: ["lollipop", "candy"], category: "Food & Drink", unicode: "U+1F36D" },
  { emoji: "🍬", name: "Candy", keywords: ["candy", "sweet"], category: "Food & Drink", unicode: "U+1F36C" },
  { emoji: "🍫", name: "Chocolate Bar", keywords: ["chocolate"], category: "Food & Drink", unicode: "U+1F36B" },
  { emoji: "🍿", name: "Popcorn", keywords: ["popcorn"], category: "Food & Drink", unicode: "U+1F37F" },
  { emoji: "🍩", name: "Doughnut", keywords: ["donut", "doughnut"], category: "Food & Drink", unicode: "U+1F369" },
  { emoji: "🍪", name: "Cookie", keywords: ["cookie"], category: "Food & Drink", unicode: "U+1F36A" },
  { emoji: "🥛", name: "Glass of Milk", keywords: ["milk"], category: "Food & Drink", unicode: "U+1F95B" },
  { emoji: "☕", name: "Hot Beverage", keywords: ["coffee", "tea"], category: "Food & Drink", unicode: "U+2615" },
  { emoji: "🍵", name: "Teacup Without Handle", keywords: ["tea"], category: "Food & Drink", unicode: "U+1F375" },
  { emoji: "🧃", name: "Beverage Box", keywords: ["juice", "box"], category: "Food & Drink", unicode: "U+1F9C3" },
  { emoji: "🥤", name: "Cup with Straw", keywords: ["soda", "drink"], category: "Food & Drink", unicode: "U+1F964" },
  { emoji: "🍶", name: "Sake", keywords: ["sake", "drink"], category: "Food & Drink", unicode: "U+1F376" },
  { emoji: "🍺", name: "Beer Mug", keywords: ["beer"], category: "Food & Drink", unicode: "U+1F37A" },
  { emoji: "🍻", name: "Clinking Beer Mugs", keywords: ["beer", "cheers"], category: "Food & Drink", unicode: "U+1F37B" },
  { emoji: "🥂", name: "Clinking Glasses", keywords: ["cheers", "champagne"], category: "Food & Drink", unicode: "U+1F942" },
  { emoji: "🍷", name: "Wine Glass", keywords: ["wine"], category: "Food & Drink", unicode: "U+1F377" },
  { emoji: "🥃", name: "Tumbler Glass", keywords: ["whiskey", "drink"], category: "Food & Drink", unicode: "U+1F943" },
  { emoji: "🍸", name: "Cocktail Glass", keywords: ["cocktail", "martini"], category: "Food & Drink", unicode: "U+1F378" },
  { emoji: "🍹", name: "Tropical Drink", keywords: ["drink", "tropical"], category: "Food & Drink", unicode: "U+1F379" },
  { emoji: "🍾", name: "Bottle with Popping Cork", keywords: ["champagne", "celebrate"], category: "Food & Drink", unicode: "U+1F37E" },

  // Activities
  { emoji: "⚽", name: "Soccer Ball", keywords: ["soccer", "football", "ball"], category: "Activities", unicode: "U+26BD" },
  { emoji: "🏀", name: "Basketball", keywords: ["basketball", "ball"], category: "Activities", unicode: "U+1F3C0" },
  { emoji: "🏈", name: "American Football", keywords: ["football", "ball"], category: "Activities", unicode: "U+1F3C8" },
  { emoji: "⚾", name: "Baseball", keywords: ["baseball", "ball"], category: "Activities", unicode: "U+26BE" },
  { emoji: "🥎", name: "Softball", keywords: ["softball", "ball"], category: "Activities", unicode: "U+1F94E" },
  { emoji: "🎾", name: "Tennis", keywords: ["tennis", "ball"], category: "Activities", unicode: "U+1F3BE" },
  { emoji: "🏐", name: "Volleyball", keywords: ["volleyball", "ball"], category: "Activities", unicode: "U+1F3D0" },
  { emoji: "🏉", name: "Rugby Football", keywords: ["rugby", "ball"], category: "Activities", unicode: "U+1F3C9" },
  { emoji: "🎱", name: "Pool 8 Ball", keywords: ["pool", "billiards", "8ball"], category: "Activities", unicode: "U+1F3B1" },
  { emoji: "🏓", name: "Ping Pong", keywords: ["ping pong", "table tennis"], category: "Activities", unicode: "U+1F3D3" },
  { emoji: "🏸", name: "Badminton", keywords: ["badminton"], category: "Activities", unicode: "U+1F3F8" },
  { emoji: "🥅", name: "Goal Net", keywords: ["goal", "net"], category: "Activities", unicode: "U+1F945" },
  { emoji: "🏒", name: "Ice Hockey", keywords: ["hockey", "ice"], category: "Activities", unicode: "U+1F3D2" },
  { emoji: "🏑", name: "Field Hockey", keywords: ["hockey", "field"], category: "Activities", unicode: "U+1F3D1" },
  { emoji: "🥍", name: "Lacrosse", keywords: ["lacrosse"], category: "Activities", unicode: "U+1F94D" },
  { emoji: "🏏", name: "Cricket Game", keywords: ["cricket"], category: "Activities", unicode: "U+1F3CF" },
  { emoji: "🥊", name: "Boxing Glove", keywords: ["boxing", "glove"], category: "Activities", unicode: "U+1F94A" },
  { emoji: "🥋", name: "Martial Arts Uniform", keywords: ["martial arts", "karate"], category: "Activities", unicode: "U+1F94B" },
  { emoji: "⛳", name: "Flag in Hole", keywords: ["golf"], category: "Activities", unicode: "U+26F3" },
  { emoji: "🏹", name: "Bow and Arrow", keywords: ["archery", "bow"], category: "Activities", unicode: "U+1F3F9" },
  { emoji: "🎣", name: "Fishing Pole", keywords: ["fishing"], category: "Activities", unicode: "U+1F3A3" },
  { emoji: "🥌", name: "Curling Stone", keywords: ["curling"], category: "Activities", unicode: "U+1F94C" },
  { emoji: "🛷", name: "Sled", keywords: ["sled", "sledding"], category: "Activities", unicode: "U+1F6F7" },
  { emoji: "🎿", name: "Skis", keywords: ["ski", "skiing"], category: "Activities", unicode: "U+1F3BF" },
  { emoji: "⛷️", name: "Skier", keywords: ["skier", "skiing"], category: "Activities", unicode: "U+26F7" },
  { emoji: "🏂", name: "Snowboarder", keywords: ["snowboard"], category: "Activities", unicode: "U+1F3C2" },
  { emoji: "🏋️", name: "Person Lifting Weights", keywords: ["weightlifting", "gym"], category: "Activities", unicode: "U+1F3CB" },
  { emoji: "🤸", name: "Person Cartwheeling", keywords: ["cartwheel", "gymnastics"], category: "Activities", unicode: "U+1F938" },
  { emoji: "🤼", name: "People Wrestling", keywords: ["wrestling"], category: "Activities", unicode: "U+1F93C" },
  { emoji: "🤽", name: "Person Playing Water Polo", keywords: ["water polo"], category: "Activities", unicode: "U+1F93D" },
  { emoji: "🤾", name: "Person Playing Handball", keywords: ["handball"], category: "Activities", unicode: "U+1F93E" },
  { emoji: "🤹", name: "Person Juggling", keywords: ["juggling"], category: "Activities", unicode: "U+1F939" },
  { emoji: "🧘", name: "Person in Lotus Position", keywords: ["yoga", "meditation"], category: "Activities", unicode: "U+1F9D8" },
  { emoji: "🏃", name: "Person Running", keywords: ["running", "run"], category: "Activities", unicode: "U+1F3C3" },
  { emoji: "🚴", name: "Person Biking", keywords: ["biking", "cycling"], category: "Activities", unicode: "U+1F6B4" },
  { emoji: "🚵", name: "Person Mountain Biking", keywords: ["mountain biking"], category: "Activities", unicode: "U+1F6B5" },
  { emoji: "🏇", name: "Horse Racing", keywords: ["horse", "racing"], category: "Activities", unicode: "U+1F3C7" },
  { emoji: "🧗", name: "Person Climbing", keywords: ["climbing", "rock climbing"], category: "Activities", unicode: "U+1F9D7" },
  { emoji: "🤺", name: "Person Fencing", keywords: ["fencing"], category: "Activities", unicode: "U+1F93A" },
  { emoji: "🏊", name: "Person Swimming", keywords: ["swimming", "swim"], category: "Activities", unicode: "U+1F3CA" },
  { emoji: "🏄", name: "Person Surfing", keywords: ["surfing", "surf"], category: "Activities", unicode: "U+1F3C4" },
  { emoji: "🚣", name: "Person Rowing Boat", keywords: ["rowing", "boat"], category: "Activities", unicode: "U+1F6A3" },
  { emoji: "🎮", name: "Video Game", keywords: ["gaming", "game", "controller"], category: "Activities", unicode: "U+1F3AE" },
  { emoji: "🕹️", name: "Joystick", keywords: ["joystick", "gaming"], category: "Activities", unicode: "U+1F579" },
  { emoji: "🎯", name: "Direct Hit", keywords: ["target", "bullseye"], category: "Activities", unicode: "U+1F3AF" },
  { emoji: "🎲", name: "Game Die", keywords: ["dice", "game"], category: "Activities", unicode: "U+1F3B2" },
  { emoji: "🎰", name: "Slot Machine", keywords: ["slot", "casino"], category: "Activities", unicode: "U+1F3B0" },
  { emoji: "🎳", name: "Bowling", keywords: ["bowling"], category: "Activities", unicode: "U+1F3B3" },
  { emoji: "🎨", name: "Artist Palette", keywords: ["art", "paint"], category: "Activities", unicode: "U+1F3A8" },
  { emoji: "🎬", name: "Clapper Board", keywords: ["movie", "film"], category: "Activities", unicode: "U+1F3AC" },
  { emoji: "🎤", name: "Microphone", keywords: ["mic", "sing"], category: "Activities", unicode: "U+1F3A4" },
  { emoji: "🎧", name: "Headphone", keywords: ["headphones", "music"], category: "Activities", unicode: "U+1F3A7" },
  { emoji: "🎼", name: "Musical Score", keywords: ["music", "notes"], category: "Activities", unicode: "U+1F3BC" },
  { emoji: "🎹", name: "Musical Keyboard", keywords: ["piano", "keyboard"], category: "Activities", unicode: "U+1F3B9" },
  { emoji: "🥁", name: "Drum", keywords: ["drum"], category: "Activities", unicode: "U+1F941" },
  { emoji: "🎷", name: "Saxophone", keywords: ["saxophone", "sax"], category: "Activities", unicode: "U+1F3B7" },
  { emoji: "🎺", name: "Trumpet", keywords: ["trumpet"], category: "Activities", unicode: "U+1F3BA" },
  { emoji: "🎸", name: "Guitar", keywords: ["guitar"], category: "Activities", unicode: "U+1F3B8" },
  { emoji: "🎻", name: "Violin", keywords: ["violin"], category: "Activities", unicode: "U+1F3BB" },
  { emoji: "🎭", name: "Performing Arts", keywords: ["theater", "drama"], category: "Activities", unicode: "U+1F3AD" },
  { emoji: "🎪", name: "Circus Tent", keywords: ["circus", "tent"], category: "Activities", unicode: "U+1F3AA" },
  { emoji: "🎟️", name: "Admission Tickets", keywords: ["tickets"], category: "Activities", unicode: "U+1F39F" },
  { emoji: "🎫", name: "Ticket", keywords: ["ticket"], category: "Activities", unicode: "U+1F3AB" },

  // Travel & Places
  { emoji: "🚗", name: "Automobile", keywords: ["car", "vehicle"], category: "Travel & Places", unicode: "U+1F697" },
  { emoji: "🚕", name: "Taxi", keywords: ["taxi", "cab"], category: "Travel & Places", unicode: "U+1F695" },
  { emoji: "🚙", name: "Sport Utility Vehicle", keywords: ["suv", "car"], category: "Travel & Places", unicode: "U+1F699" },
  { emoji: "🚌", name: "Bus", keywords: ["bus"], category: "Travel & Places", unicode: "U+1F68C" },
  { emoji: "🚎", name: "Trolleybus", keywords: ["trolleybus"], category: "Travel & Places", unicode: "U+1F68E" },
  { emoji: "🏎️", name: "Racing Car", keywords: ["race car", "formula"], category: "Travel & Places", unicode: "U+1F3CE" },
  { emoji: "🚓", name: "Police Car", keywords: ["police", "car"], category: "Travel & Places", unicode: "U+1F693" },
  { emoji: "🚑", name: "Ambulance", keywords: ["ambulance"], category: "Travel & Places", unicode: "U+1F691" },
  { emoji: "🚒", name: "Fire Engine", keywords: ["fire truck"], category: "Travel & Places", unicode: "U+1F692" },
  { emoji: "🚐", name: "Minibus", keywords: ["minibus", "van"], category: "Travel & Places", unicode: "U+1F690" },
  { emoji: "🚚", name: "Delivery Truck", keywords: ["truck", "delivery"], category: "Travel & Places", unicode: "U+1F69A" },
  { emoji: "🚛", name: "Articulated Lorry", keywords: ["truck", "semi"], category: "Travel & Places", unicode: "U+1F69B" },
  { emoji: "🚜", name: "Tractor", keywords: ["tractor", "farm"], category: "Travel & Places", unicode: "U+1F69C" },
  { emoji: "🏍️", name: "Motorcycle", keywords: ["motorcycle", "bike"], category: "Travel & Places", unicode: "U+1F3CD" },
  { emoji: "🛵", name: "Motor Scooter", keywords: ["scooter", "moped"], category: "Travel & Places", unicode: "U+1F6F5" },
  { emoji: "🚲", name: "Bicycle", keywords: ["bicycle", "bike"], category: "Travel & Places", unicode: "U+1F6B2" },
  { emoji: "🛴", name: "Kick Scooter", keywords: ["scooter"], category: "Travel & Places", unicode: "U+1F6F4" },
  { emoji: "🚏", name: "Bus Stop", keywords: ["bus stop"], category: "Travel & Places", unicode: "U+1F68F" },
  { emoji: "🛣️", name: "Motorway", keywords: ["highway", "road"], category: "Travel & Places", unicode: "U+1F6E3" },
  { emoji: "🛤️", name: "Railway Track", keywords: ["railway", "track"], category: "Travel & Places", unicode: "U+1F6E4" },
  { emoji: "⛽", name: "Fuel Pump", keywords: ["gas", "fuel"], category: "Travel & Places", unicode: "U+26FD" },
  { emoji: "🚨", name: "Police Car Light", keywords: ["police", "siren"], category: "Travel & Places", unicode: "U+1F6A8" },
  { emoji: "🚥", name: "Horizontal Traffic Light", keywords: ["traffic light"], category: "Travel & Places", unicode: "U+1F6A5" },
  { emoji: "🚦", name: "Vertical Traffic Light", keywords: ["traffic light"], category: "Travel & Places", unicode: "U+1F6A6" },
  { emoji: "🚧", name: "Construction", keywords: ["construction"], category: "Travel & Places", unicode: "U+1F6A7" },
  { emoji: "⚓", name: "Anchor", keywords: ["anchor", "ship"], category: "Travel & Places", unicode: "U+2693" },
  { emoji: "⛵", name: "Sailboat", keywords: ["sailboat", "boat"], category: "Travel & Places", unicode: "U+26F5" },
  { emoji: "🚤", name: "Speedboat", keywords: ["speedboat", "boat"], category: "Travel & Places", unicode: "U+1F6A4" },
  { emoji: "🛳️", name: "Passenger Ship", keywords: ["cruise", "ship"], category: "Travel & Places", unicode: "U+1F6F3" },
  { emoji: "⛴️", name: "Ferry", keywords: ["ferry", "boat"], category: "Travel & Places", unicode: "U+26F4" },
  { emoji: "🛥️", name: "Motor Boat", keywords: ["motor boat"], category: "Travel & Places", unicode: "U+1F6E5" },
  { emoji: "🚢", name: "Ship", keywords: ["ship", "boat"], category: "Travel & Places", unicode: "U+1F6A2" },
  { emoji: "✈️", name: "Airplane", keywords: ["airplane", "plane"], category: "Travel & Places", unicode: "U+2708" },
  { emoji: "🛩️", name: "Small Airplane", keywords: ["small plane"], category: "Travel & Places", unicode: "U+1F6E9" },
  { emoji: "🛫", name: "Airplane Departure", keywords: ["takeoff", "plane"], category: "Travel & Places", unicode: "U+1F6EB" },
  { emoji: "🛬", name: "Airplane Arrival", keywords: ["landing", "plane"], category: "Travel & Places", unicode: "U+1F6EC" },
  { emoji: "🚁", name: "Helicopter", keywords: ["helicopter"], category: "Travel & Places", unicode: "U+1F681" },
  { emoji: "🚟", name: "Suspension Railway", keywords: ["railway"], category: "Travel & Places", unicode: "U+1F69F" },
  { emoji: "🚠", name: "Mountain Cableway", keywords: ["cable car"], category: "Travel & Places", unicode: "U+1F6A0" },
  { emoji: "🚡", name: "Aerial Tramway", keywords: ["tramway", "cable"], category: "Travel & Places", unicode: "U+1F6A1" },
  { emoji: "🛰️", name: "Satellite", keywords: ["satellite", "space"], category: "Travel & Places", unicode: "U+1F6F0" },
  { emoji: "🚀", name: "Rocket", keywords: ["rocket", "space"], category: "Travel & Places", unicode: "U+1F680" },
  { emoji: "🛸", name: "Flying Saucer", keywords: ["ufo", "alien"], category: "Travel & Places", unicode: "U+1F6F8" },
  { emoji: "🚆", name: "Train", keywords: ["train"], category: "Travel & Places", unicode: "U+1F686" },
  { emoji: "🚇", name: "Metro", keywords: ["metro", "subway"], category: "Travel & Places", unicode: "U+1F687" },
  { emoji: "🚊", name: "Tram", keywords: ["tram"], category: "Travel & Places", unicode: "U+1F68A" },
  { emoji: "🚝", name: "Monorail", keywords: ["monorail"], category: "Travel & Places", unicode: "U+1F69D" },
  { emoji: "🚈", name: "Light Rail", keywords: ["light rail"], category: "Travel & Places", unicode: "U+1F688" },
  { emoji: "🚉", name: "Station", keywords: ["station", "train"], category: "Travel & Places", unicode: "U+1F689" },
  { emoji: "🚂", name: "Locomotive", keywords: ["locomotive", "train"], category: "Travel & Places", unicode: "U+1F682" },
  { emoji: "🚃", name: "Railway Car", keywords: ["railway car"], category: "Travel & Places", unicode: "U+1F683" },
  { emoji: "🚄", name: "High-Speed Train", keywords: ["bullet train"], category: "Travel & Places", unicode: "U+1F684" },
  { emoji: "🚅", name: "Bullet Train", keywords: ["bullet train"], category: "Travel & Places", unicode: "U+1F685" },
  { emoji: "🚞", name: "Mountain Railway", keywords: ["mountain railway"], category: "Travel & Places", unicode: "U+1F69E" },
  { emoji: "🚋", name: "Tram Car", keywords: ["tram"], category: "Travel & Places", unicode: "U+1F68B" },
  { emoji: "🏠", name: "House", keywords: ["house", "home"], category: "Travel & Places", unicode: "U+1F3E0" },
  { emoji: "🏡", name: "House with Garden", keywords: ["house", "garden"], category: "Travel & Places", unicode: "U+1F3E1" },
  { emoji: "🏢", name: "Office Building", keywords: ["office", "building"], category: "Travel & Places", unicode: "U+1F3E2" },
  { emoji: "🏣", name: "Japanese Post Office", keywords: ["post office"], category: "Travel & Places", unicode: "U+1F3E3" },
  { emoji: "🏤", name: "Post Office", keywords: ["post office"], category: "Travel & Places", unicode: "U+1F3E4" },
  { emoji: "🏥", name: "Hospital", keywords: ["hospital"], category: "Travel & Places", unicode: "U+1F3E5" },
  { emoji: "🏦", name: "Bank", keywords: ["bank"], category: "Travel & Places", unicode: "U+1F3E6" },
  { emoji: "🏨", name: "Hotel", keywords: ["hotel"], category: "Travel & Places", unicode: "U+1F3E8" },
  { emoji: "🏩", name: "Love Hotel", keywords: ["love hotel"], category: "Travel & Places", unicode: "U+1F3E9" },
  { emoji: "🏪", name: "Convenience Store", keywords: ["store", "shop"], category: "Travel & Places", unicode: "U+1F3EA" },
  { emoji: "🏫", name: "School", keywords: ["school"], category: "Travel & Places", unicode: "U+1F3EB" },
  { emoji: "🏬", name: "Department Store", keywords: ["department store"], category: "Travel & Places", unicode: "U+1F3EC" },
  { emoji: "🏭", name: "Factory", keywords: ["factory"], category: "Travel & Places", unicode: "U+1F3ED" },
  { emoji: "🏯", name: "Japanese Castle", keywords: ["castle"], category: "Travel & Places", unicode: "U+1F3EF" },
  { emoji: "🏰", name: "Castle", keywords: ["castle"], category: "Travel & Places", unicode: "U+1F3F0" },
  { emoji: "💒", name: "Wedding", keywords: ["wedding", "chapel"], category: "Travel & Places", unicode: "U+1F492" },
  { emoji: "🗼", name: "Tokyo Tower", keywords: ["tower", "tokyo"], category: "Travel & Places", unicode: "U+1F5FC" },
  { emoji: "🗽", name: "Statue of Liberty", keywords: ["statue", "liberty"], category: "Travel & Places", unicode: "U+1F5FD" },
  { emoji: "⛪", name: "Church", keywords: ["church"], category: "Travel & Places", unicode: "U+26EA" },
  { emoji: "🕌", name: "Mosque", keywords: ["mosque"], category: "Travel & Places", unicode: "U+1F54C" },
  { emoji: "🛕", name: "Hindu Temple", keywords: ["temple", "hindu"], category: "Travel & Places", unicode: "U+1F6D5" },
  { emoji: "🕍", name: "Synagogue", keywords: ["synagogue"], category: "Travel & Places", unicode: "U+1F54D" },
  { emoji: "⛩️", name: "Shinto Shrine", keywords: ["shrine", "shinto"], category: "Travel & Places", unicode: "U+26E9" },
  { emoji: "🕋", name: "Kaaba", keywords: ["kaaba"], category: "Travel & Places", unicode: "U+1F54B" },
  { emoji: "⛲", name: "Fountain", keywords: ["fountain"], category: "Travel & Places", unicode: "U+26F2" },
  { emoji: "⛺", name: "Tent", keywords: ["tent", "camping"], category: "Travel & Places", unicode: "U+26FA" },
  { emoji: "🌁", name: "Foggy", keywords: ["fog", "foggy"], category: "Travel & Places", unicode: "U+1F301" },
  { emoji: "🌃", name: "Night with Stars", keywords: ["night", "stars"], category: "Travel & Places", unicode: "U+1F303" },
  { emoji: "🏙️", name: "Cityscape", keywords: ["city", "buildings"], category: "Travel & Places", unicode: "U+1F3D9" },
  { emoji: "🌄", name: "Sunrise Over Mountains", keywords: ["sunrise", "mountains"], category: "Travel & Places", unicode: "U+1F304" },
  { emoji: "🌅", name: "Sunrise", keywords: ["sunrise"], category: "Travel & Places", unicode: "U+1F305" },
  { emoji: "🌆", name: "Cityscape at Dusk", keywords: ["city", "dusk"], category: "Travel & Places", unicode: "U+1F306" },
  { emoji: "🌇", name: "Sunset", keywords: ["sunset"], category: "Travel & Places", unicode: "U+1F307" },
  { emoji: "🌉", name: "Bridge at Night", keywords: ["bridge", "night"], category: "Travel & Places", unicode: "U+1F309" },
  { emoji: "🌌", name: "Milky Way", keywords: ["milky way", "stars"], category: "Travel & Places", unicode: "U+1F30C" },
  { emoji: "🎠", name: "Carousel Horse", keywords: ["carousel", "horse"], category: "Travel & Places", unicode: "U+1F3A0" },
  { emoji: "🎡", name: "Ferris Wheel", keywords: ["ferris wheel"], category: "Travel & Places", unicode: "U+1F3A1" },
  { emoji: "🎢", name: "Roller Coaster", keywords: ["roller coaster"], category: "Travel & Places", unicode: "U+1F3A2" },
  { emoji: "🚂", name: "Steam Locomotive", keywords: ["locomotive", "steam"], category: "Travel & Places", unicode: "U+1F682" },

  // Objects
  { emoji: "⌚", name: "Watch", keywords: ["watch", "time"], category: "Objects", unicode: "U+231A" },
  { emoji: "📱", name: "Mobile Phone", keywords: ["phone", "mobile"], category: "Objects", unicode: "U+1F4F1" },
  { emoji: "💻", name: "Laptop", keywords: ["laptop", "computer"], category: "Objects", unicode: "U+1F4BB" },
  { emoji: "⌨️", name: "Keyboard", keywords: ["keyboard"], category: "Objects", unicode: "U+2328" },
  { emoji: "🖥️", name: "Desktop Computer", keywords: ["computer", "desktop"], category: "Objects", unicode: "U+1F5A5" },
  { emoji: "🖨️", name: "Printer", keywords: ["printer"], category: "Objects", unicode: "U+1F5A8" },
  { emoji: "🖱️", name: "Computer Mouse", keywords: ["mouse", "computer"], category: "Objects", unicode: "U+1F5B1" },
  { emoji: "🖲️", name: "Trackball", keywords: ["trackball"], category: "Objects", unicode: "U+1F5B2" },
  { emoji: "💽", name: "Computer Disk", keywords: ["disk", "minidisc"], category: "Objects", unicode: "U+1F4BD" },
  { emoji: "💾", name: "Floppy Disk", keywords: ["floppy", "disk", "save"], category: "Objects", unicode: "U+1F4BE" },
  { emoji: "💿", name: "Optical Disk", keywords: ["cd", "disk"], category: "Objects", unicode: "U+1F4BF" },
  { emoji: "📀", name: "DVD", keywords: ["dvd", "disk"], category: "Objects", unicode: "U+1F4C0" },
  { emoji: "🎥", name: "Movie Camera", keywords: ["camera", "movie"], category: "Objects", unicode: "U+1F3A5" },
  { emoji: "📷", name: "Camera", keywords: ["camera", "photo"], category: "Objects", unicode: "U+1F4F7" },
  { emoji: "📹", name: "Video Camera", keywords: ["camera", "video"], category: "Objects", unicode: "U+1F4F9" },
  { emoji: "📼", name: "Videocassette", keywords: ["vhs", "tape"], category: "Objects", unicode: "U+1F4FC" },
  { emoji: "🔍", name: "Magnifying Glass Tilted Left", keywords: ["search", "magnify"], category: "Objects", unicode: "U+1F50D" },
  { emoji: "🔎", name: "Magnifying Glass Tilted Right", keywords: ["search", "magnify"], category: "Objects", unicode: "U+1F50E" },
  { emoji: "💡", name: "Light Bulb", keywords: ["light", "idea"], category: "Objects", unicode: "U+1F4A1" },
  { emoji: "🔦", name: "Flashlight", keywords: ["flashlight", "torch"], category: "Objects", unicode: "U+1F526" },
  { emoji: "🕯️", name: "Candle", keywords: ["candle"], category: "Objects", unicode: "U+1F56F" },
  { emoji: "💰", name: "Money Bag", keywords: ["money", "bag"], category: "Objects", unicode: "U+1F4B0" },
  { emoji: "💵", name: "Dollar Banknote", keywords: ["dollar", "money"], category: "Objects", unicode: "U+1F4B5" },
  { emoji: "💴", name: "Yen Banknote", keywords: ["yen", "money"], category: "Objects", unicode: "U+1F4B4" },
  { emoji: "💶", name: "Euro Banknote", keywords: ["euro", "money"], category: "Objects", unicode: "U+1F4B6" },
  { emoji: "💷", name: "Pound Banknote", keywords: ["pound", "money"], category: "Objects", unicode: "U+1F4B7" },
  { emoji: "💳", name: "Credit Card", keywords: ["credit card", "card"], category: "Objects", unicode: "U+1F4B3" },
  { emoji: "💎", name: "Gem Stone", keywords: ["gem", "diamond"], category: "Objects", unicode: "U+1F48E" },
  { emoji: "🔨", name: "Hammer", keywords: ["hammer", "tool"], category: "Objects", unicode: "U+1F528" },
  { emoji: "🔧", name: "Wrench", keywords: ["wrench", "tool"], category: "Objects", unicode: "U+1F527" },
  { emoji: "🔩", name: "Nut and Bolt", keywords: ["nut", "bolt"], category: "Objects", unicode: "U+1F529" },
  { emoji: "⚙️", name: "Gear", keywords: ["gear", "settings"], category: "Objects", unicode: "U+2699" },
  { emoji: "🔫", name: "Pistol", keywords: ["gun", "pistol"], category: "Objects", unicode: "U+1F52B" },
  { emoji: "💣", name: "Bomb", keywords: ["bomb"], category: "Objects", unicode: "U+1F4A3" },
  { emoji: "🔪", name: "Kitchen Knife", keywords: ["knife"], category: "Objects", unicode: "U+1F52A" },
  { emoji: "🗡️", name: "Dagger", keywords: ["dagger", "knife"], category: "Objects", unicode: "U+1F5E1" },
  { emoji: "⚔️", name: "Crossed Swords", keywords: ["swords", "battle"], category: "Objects", unicode: "U+2694" },
  { emoji: "🛡️", name: "Shield", keywords: ["shield"], category: "Objects", unicode: "U+1F6E1" },
  { emoji: "🔮", name: "Crystal Ball", keywords: ["crystal ball", "fortune"], category: "Objects", unicode: "U+1F52E" },
  { emoji: "💊", name: "Pill", keywords: ["pill", "medicine"], category: "Objects", unicode: "U+1F48A" },
  { emoji: "💉", name: "Syringe", keywords: ["syringe", "needle"], category: "Objects", unicode: "U+1F489" },
  { emoji: "🔑", name: "Key", keywords: ["key"], category: "Objects", unicode: "U+1F511" },
  { emoji: "🗝️", name: "Old Key", keywords: ["key", "old"], category: "Objects", unicode: "U+1F5DD" },
  { emoji: "🚪", name: "Door", keywords: ["door"], category: "Objects", unicode: "U+1F6AA" },
  { emoji: "🛋️", name: "Couch and Lamp", keywords: ["couch", "sofa"], category: "Objects", unicode: "U+1F6CB" },
  { emoji: "🛏️", name: "Bed", keywords: ["bed"], category: "Objects", unicode: "U+1F6CF" },
  { emoji: "🚽", name: "Toilet", keywords: ["toilet"], category: "Objects", unicode: "U+1F6BD" },
  { emoji: "🚿", name: "Shower", keywords: ["shower"], category: "Objects", unicode: "U+1F6BF" },
  { emoji: "🛁", name: "Bathtub", keywords: ["bathtub", "bath"], category: "Objects", unicode: "U+1F6C1" },
  { emoji: "⏰", name: "Alarm Clock", keywords: ["alarm", "clock"], category: "Objects", unicode: "U+23F0" },
  { emoji: "⏱️", name: "Stopwatch", keywords: ["stopwatch", "timer"], category: "Objects", unicode: "U+23F1" },
  { emoji: "⏲️", name: "Timer Clock", keywords: ["timer", "clock"], category: "Objects", unicode: "U+23F2" },
  { emoji: "🕰️", name: "Mantelpiece Clock", keywords: ["clock"], category: "Objects", unicode: "U+1F570" },
  { emoji: "📚", name: "Books", keywords: ["books", "library"], category: "Objects", unicode: "U+1F4DA" },
  { emoji: "📖", name: "Open Book", keywords: ["book", "open"], category: "Objects", unicode: "U+1F4D6" },
  { emoji: "📝", name: "Memo", keywords: ["memo", "note"], category: "Objects", unicode: "U+1F4DD" },
  { emoji: "✏️", name: "Pencil", keywords: ["pencil"], category: "Objects", unicode: "U+270F" },
  { emoji: "✒️", name: "Black Nib", keywords: ["pen", "nib"], category: "Objects", unicode: "U+2712" },
  { emoji: "🖊️", name: "Pen", keywords: ["pen"], category: "Objects", unicode: "U+1F58A" },
  { emoji: "🖍️", name: "Crayon", keywords: ["crayon"], category: "Objects", unicode: "U+1F58D" },
  { emoji: "📌", name: "Pushpin", keywords: ["pin", "pushpin"], category: "Objects", unicode: "U+1F4CC" },
  { emoji: "📍", name: "Round Pushpin", keywords: ["pin", "location"], category: "Objects", unicode: "U+1F4CD" },
  { emoji: "✂️", name: "Scissors", keywords: ["scissors", "cut"], category: "Objects", unicode: "U+2702" },
  { emoji: "🔒", name: "Locked", keywords: ["lock", "locked"], category: "Objects", unicode: "U+1F512" },
  { emoji: "🔓", name: "Unlocked", keywords: ["unlock", "unlocked"], category: "Objects", unicode: "U+1F513" },
  { emoji: "🔐", name: "Locked with Key", keywords: ["lock", "key"], category: "Objects", unicode: "U+1F510" },
  { emoji: "🔏", name: "Locked with Pen", keywords: ["lock", "pen"], category: "Objects", unicode: "U+1F50F" },

  // Symbols
  { emoji: "❤️", name: "Red Heart", keywords: ["love", "heart"], category: "Symbols", unicode: "U+2764" },
  { emoji: "🧡", name: "Orange Heart", keywords: ["love", "heart"], category: "Symbols", unicode: "U+1F9E1" },
  { emoji: "💛", name: "Yellow Heart", keywords: ["love", "heart"], category: "Symbols", unicode: "U+1F49B" },
  { emoji: "💚", name: "Green Heart", keywords: ["love", "heart"], category: "Symbols", unicode: "U+1F49A" },
  { emoji: "💙", name: "Blue Heart", keywords: ["love", "heart"], category: "Symbols", unicode: "U+1F499" },
  { emoji: "💜", name: "Purple Heart", keywords: ["love", "heart"], category: "Symbols", unicode: "U+1F49C" },
  { emoji: "🖤", name: "Black Heart", keywords: ["love", "heart"], category: "Symbols", unicode: "U+1F5A4" },
  { emoji: "🤍", name: "White Heart", keywords: ["love", "heart"], category: "Symbols", unicode: "U+1F90D" },
  { emoji: "🤎", name: "Brown Heart", keywords: ["love", "heart"], category: "Symbols", unicode: "U+1F90E" },
  { emoji: "💔", name: "Broken Heart", keywords: ["broken", "heart"], category: "Symbols", unicode: "U+1F494" },
  { emoji: "❣️", name: "Heart Exclamation", keywords: ["heart", "exclamation"], category: "Symbols", unicode: "U+2763" },
  { emoji: "💕", name: "Two Hearts", keywords: ["hearts", "love"], category: "Symbols", unicode: "U+1F495" },
  { emoji: "💞", name: "Revolving Hearts", keywords: ["hearts", "love"], category: "Symbols", unicode: "U+1F49E" },
  { emoji: "💓", name: "Beating Heart", keywords: ["heart", "beating"], category: "Symbols", unicode: "U+1F493" },
  { emoji: "💗", name: "Growing Heart", keywords: ["heart", "growing"], category: "Symbols", unicode: "U+1F497" },
  { emoji: "💖", name: "Sparkling Heart", keywords: ["heart", "sparkle"], category: "Symbols", unicode: "U+1F496" },
  { emoji: "💘", name: "Heart with Arrow", keywords: ["heart", "arrow", "love"], category: "Symbols", unicode: "U+1F498" },
  { emoji: "💝", name: "Heart with Ribbon", keywords: ["heart", "gift"], category: "Symbols", unicode: "U+1F49D" },
  { emoji: "✅", name: "Check Mark Button", keywords: ["check", "yes", "done"], category: "Symbols", unicode: "U+2705" },
  { emoji: "❌", name: "Cross Mark", keywords: ["x", "no", "wrong"], category: "Symbols", unicode: "U+274C" },
  { emoji: "❓", name: "Question Mark", keywords: ["question"], category: "Symbols", unicode: "U+2753" },
  { emoji: "❗", name: "Exclamation Mark", keywords: ["exclamation"], category: "Symbols", unicode: "U+2757" },
  { emoji: "💯", name: "Hundred Points", keywords: ["100", "perfect"], category: "Symbols", unicode: "U+1F4AF" },
  { emoji: "🔴", name: "Red Circle", keywords: ["red", "circle"], category: "Symbols", unicode: "U+1F534" },
  { emoji: "🟠", name: "Orange Circle", keywords: ["orange", "circle"], category: "Symbols", unicode: "U+1F7E0" },
  { emoji: "🟡", name: "Yellow Circle", keywords: ["yellow", "circle"], category: "Symbols", unicode: "U+1F7E1" },
  { emoji: "🟢", name: "Green Circle", keywords: ["green", "circle"], category: "Symbols", unicode: "U+1F7E2" },
  { emoji: "🔵", name: "Blue Circle", keywords: ["blue", "circle"], category: "Symbols", unicode: "U+1F535" },
  { emoji: "🟣", name: "Purple Circle", keywords: ["purple", "circle"], category: "Symbols", unicode: "U+1F7E3" },
  { emoji: "⚫", name: "Black Circle", keywords: ["black", "circle"], category: "Symbols", unicode: "U+26AB" },
  { emoji: "⚪", name: "White Circle", keywords: ["white", "circle"], category: "Symbols", unicode: "U+26AA" },
  { emoji: "🟤", name: "Brown Circle", keywords: ["brown", "circle"], category: "Symbols", unicode: "U+1F7E4" },
  { emoji: "⭐", name: "Star", keywords: ["star"], category: "Symbols", unicode: "U+2B50" },
  { emoji: "🌟", name: "Glowing Star", keywords: ["star", "glow"], category: "Symbols", unicode: "U+1F31F" },
  { emoji: "✨", name: "Sparkles", keywords: ["sparkles", "stars"], category: "Symbols", unicode: "U+2728" },
  { emoji: "💫", name: "Dizzy", keywords: ["dizzy", "star"], category: "Symbols", unicode: "U+1F4AB" },
  { emoji: "🔥", name: "Fire", keywords: ["fire", "flame"], category: "Symbols", unicode: "U+1F525" },
  { emoji: "💥", name: "Collision", keywords: ["boom", "explosion"], category: "Symbols", unicode: "U+1F4A5" },
  { emoji: "💢", name: "Anger Symbol", keywords: ["anger", "angry"], category: "Symbols", unicode: "U+1F4A2" },
  { emoji: "💦", name: "Sweat Droplets", keywords: ["sweat", "water"], category: "Symbols", unicode: "U+1F4A6" },
  { emoji: "💨", name: "Dashing Away", keywords: ["dash", "wind"], category: "Symbols", unicode: "U+1F4A8" },
  { emoji: "💬", name: "Speech Balloon", keywords: ["speech", "talk"], category: "Symbols", unicode: "U+1F4AC" },
  { emoji: "💭", name: "Thought Balloon", keywords: ["thought", "think"], category: "Symbols", unicode: "U+1F4AD" },
  { emoji: "💤", name: "Zzz", keywords: ["sleep", "zzz"], category: "Symbols", unicode: "U+1F4A4" },
  { emoji: "🔔", name: "Bell", keywords: ["bell", "notification"], category: "Symbols", unicode: "U+1F514" },
  { emoji: "🔕", name: "Bell with Slash", keywords: ["bell", "mute"], category: "Symbols", unicode: "U+1F515" },
  { emoji: "🔇", name: "Muted Speaker", keywords: ["mute", "speaker"], category: "Symbols", unicode: "U+1F507" },
  { emoji: "🔈", name: "Speaker Low Volume", keywords: ["speaker", "volume"], category: "Symbols", unicode: "U+1F508" },
  { emoji: "🔉", name: "Speaker Medium Volume", keywords: ["speaker", "volume"], category: "Symbols", unicode: "U+1F509" },
  { emoji: "🔊", name: "Speaker High Volume", keywords: ["speaker", "loud"], category: "Symbols", unicode: "U+1F50A" },
  { emoji: "♠️", name: "Spade Suit", keywords: ["spade", "card"], category: "Symbols", unicode: "U+2660" },
  { emoji: "♣️", name: "Club Suit", keywords: ["club", "card"], category: "Symbols", unicode: "U+2663" },
  { emoji: "♥️", name: "Heart Suit", keywords: ["heart", "card"], category: "Symbols", unicode: "U+2665" },
  { emoji: "♦️", name: "Diamond Suit", keywords: ["diamond", "card"], category: "Symbols", unicode: "U+2666" },
  { emoji: "🎵", name: "Musical Note", keywords: ["music", "note"], category: "Symbols", unicode: "U+1F3B5" },
  { emoji: "🎶", name: "Musical Notes", keywords: ["music", "notes"], category: "Symbols", unicode: "U+1F3B6" },
  { emoji: "♻️", name: "Recycling Symbol", keywords: ["recycle"], category: "Symbols", unicode: "U+267B" },
  { emoji: "🔰", name: "Japanese Symbol for Beginner", keywords: ["beginner"], category: "Symbols", unicode: "U+1F530" },
  { emoji: "⚠️", name: "Warning", keywords: ["warning", "caution"], category: "Symbols", unicode: "U+26A0" },
  { emoji: "🚸", name: "Children Crossing", keywords: ["children", "crossing"], category: "Symbols", unicode: "U+1F6B8" },
  { emoji: "⛔", name: "No Entry", keywords: ["no entry", "stop"], category: "Symbols", unicode: "U+26D4" },
  { emoji: "🚫", name: "Prohibited", keywords: ["no", "prohibited"], category: "Symbols", unicode: "U+1F6AB" },
  { emoji: "🚳", name: "No Bicycles", keywords: ["no bicycles"], category: "Symbols", unicode: "U+1F6B3" },
  { emoji: "🚭", name: "No Smoking", keywords: ["no smoking"], category: "Symbols", unicode: "U+1F6AD" },
  { emoji: "🚯", name: "No Littering", keywords: ["no littering"], category: "Symbols", unicode: "U+1F6AF" },
  { emoji: "🚱", name: "Non-Potable Water", keywords: ["no water"], category: "Symbols", unicode: "U+1F6B1" },
  { emoji: "🚷", name: "No Pedestrians", keywords: ["no pedestrians"], category: "Symbols", unicode: "U+1F6B7" },
  { emoji: "📵", name: "No Mobile Phones", keywords: ["no phone"], category: "Symbols", unicode: "U+1F4F5" },
  { emoji: "🔞", name: "No One Under Eighteen", keywords: ["18", "adult"], category: "Symbols", unicode: "U+1F51E" },
  { emoji: "☢️", name: "Radioactive", keywords: ["radioactive"], category: "Symbols", unicode: "U+2622" },
  { emoji: "☣️", name: "Biohazard", keywords: ["biohazard"], category: "Symbols", unicode: "U+2623" },

  // Flags
  { emoji: "🏁", name: "Chequered Flag", keywords: ["checkered", "racing"], category: "Flags", unicode: "U+1F3C1" },
  { emoji: "🚩", name: "Triangular Flag", keywords: ["flag", "red"], category: "Flags", unicode: "U+1F6A9" },
  { emoji: "🎌", name: "Crossed Flags", keywords: ["flags", "japan"], category: "Flags", unicode: "U+1F38C" },
  { emoji: "🏴", name: "Black Flag", keywords: ["flag", "black"], category: "Flags", unicode: "U+1F3F4" },
  { emoji: "🏳️", name: "White Flag", keywords: ["flag", "white"], category: "Flags", unicode: "U+1F3F3" },
  { emoji: "🇺🇸", name: "United States", keywords: ["usa", "america", "us"], category: "Flags", unicode: "U+1F1FA U+1F1F8" },
  { emoji: "🇬🇧", name: "United Kingdom", keywords: ["uk", "britain", "gb"], category: "Flags", unicode: "U+1F1EC U+1F1E7" },
  { emoji: "🇨🇦", name: "Canada", keywords: ["canada", "ca"], category: "Flags", unicode: "U+1F1E8 U+1F1E6" },
  { emoji: "🇫🇷", name: "France", keywords: ["france", "fr"], category: "Flags", unicode: "U+1F1EB U+1F1F7" },
  { emoji: "🇩🇪", name: "Germany", keywords: ["germany", "de"], category: "Flags", unicode: "U+1F1E9 U+1F1EA" },
  { emoji: "🇮🇹", name: "Italy", keywords: ["italy", "it"], category: "Flags", unicode: "U+1F1EE U+1F1F9" },
  { emoji: "🇪🇸", name: "Spain", keywords: ["spain", "es"], category: "Flags", unicode: "U+1F1EA U+1F1F8" },
  { emoji: "🇯🇵", name: "Japan", keywords: ["japan", "jp"], category: "Flags", unicode: "U+1F1EF U+1F1F5" },
  { emoji: "🇨🇳", name: "China", keywords: ["china", "cn"], category: "Flags", unicode: "U+1F1E8 U+1F1F3" },
  { emoji: "🇰🇷", name: "South Korea", keywords: ["korea", "south", "kr"], category: "Flags", unicode: "U+1F1F0 U+1F1F7" },
  { emoji: "🇮🇳", name: "India", keywords: ["india", "in"], category: "Flags", unicode: "U+1F1EE U+1F1F3" },
  { emoji: "🇧🇷", name: "Brazil", keywords: ["brazil", "br"], category: "Flags", unicode: "U+1F1E7 U+1F1F7" },
  { emoji: "🇲🇽", name: "Mexico", keywords: ["mexico", "mx"], category: "Flags", unicode: "U+1F1F2 U+1F1FD" },
  { emoji: "🇦🇺", name: "Australia", keywords: ["australia", "au"], category: "Flags", unicode: "U+1F1E6 U+1F1FA" },
  { emoji: "🇷🇺", name: "Russia", keywords: ["russia", "ru"], category: "Flags", unicode: "U+1F1F7 U+1F1FA" },
  { emoji: "🇿🇦", name: "South Africa", keywords: ["south africa", "za"], category: "Flags", unicode: "U+1F1FF U+1F1E6" },
  { emoji: "🇦🇷", name: "Argentina", keywords: ["argentina", "ar"], category: "Flags", unicode: "U+1F1E6 U+1F1F7" },
  { emoji: "🇨🇱", name: "Chile", keywords: ["chile", "cl"], category: "Flags", unicode: "U+1F1E8 U+1F1F1" },
  { emoji: "🇨🇴", name: "Colombia", keywords: ["colombia", "co"], category: "Flags", unicode: "U+1F1E8 U+1F1F4" },
  { emoji: "🇻🇪", name: "Venezuela", keywords: ["venezuela", "ve"], category: "Flags", unicode: "U+1F1FB U+1F1EA" },
  { emoji: "🇵🇪", name: "Peru", keywords: ["peru", "pe"], category: "Flags", unicode: "U+1F1F5 U+1F1EA" },
  { emoji: "🇪🇬", name: "Egypt", keywords: ["egypt", "eg"], category: "Flags", unicode: "U+1F1EA U+1F1EC" },
  { emoji: "🇳🇬", name: "Nigeria", keywords: ["nigeria", "ng"], category: "Flags", unicode: "U+1F1F3 U+1F1EC" },
  { emoji: "🇰🇪", name: "Kenya", keywords: ["kenya", "ke"], category: "Flags", unicode: "U+1F1F0 U+1F1EA" },
  { emoji: "🇸🇦", name: "Saudi Arabia", keywords: ["saudi", "arabia", "sa"], category: "Flags", unicode: "U+1F1F8 U+1F1E6" },
  { emoji: "🇦🇪", name: "United Arab Emirates", keywords: ["uae", "emirates", "ae"], category: "Flags", unicode: "U+1F1E6 U+1F1EA" },
  { emoji: "🇮🇱", name: "Israel", keywords: ["israel", "il"], category: "Flags", unicode: "U+1F1EE U+1F1F1" },
  { emoji: "🇹🇷", name: "Turkey", keywords: ["turkey", "tr"], category: "Flags", unicode: "U+1F1F9 U+1F1F7" },
  { emoji: "🇬🇷", name: "Greece", keywords: ["greece", "gr"], category: "Flags", unicode: "U+1F1EC U+1F1F7" },
  { emoji: "🇵🇱", name: "Poland", keywords: ["poland", "pl"], category: "Flags", unicode: "U+1F1F5 U+1F1F1" },
  { emoji: "🇳🇱", name: "Netherlands", keywords: ["netherlands", "nl"], category: "Flags", unicode: "U+1F1F3 U+1F1F1" },
  { emoji: "🇧🇪", name: "Belgium", keywords: ["belgium", "be"], category: "Flags", unicode: "U+1F1E7 U+1F1EA" },
  { emoji: "🇨🇭", name: "Switzerland", keywords: ["switzerland", "ch"], category: "Flags", unicode: "U+1F1E8 U+1F1ED" },
  { emoji: "🇸🇪", name: "Sweden", keywords: ["sweden", "se"], category: "Flags", unicode: "U+1F1F8 U+1F1EA" },
  { emoji: "🇳🇴", name: "Norway", keywords: ["norway", "no"], category: "Flags", unicode: "U+1F1F3 U+1F1F4" },
  { emoji: "🇩🇰", name: "Denmark", keywords: ["denmark", "dk"], category: "Flags", unicode: "U+1F1E9 U+1F1F0" },
  { emoji: "🇫🇮", name: "Finland", keywords: ["finland", "fi"], category: "Flags", unicode: "U+1F1EB U+1F1EE" },
  { emoji: "🇮🇪", name: "Ireland", keywords: ["ireland", "ie"], category: "Flags", unicode: "U+1F1EE U+1F1EA" },
  { emoji: "🇵🇹", name: "Portugal", keywords: ["portugal", "pt"], category: "Flags", unicode: "U+1F1F5 U+1F1F9" },
  { emoji: "🇦🇹", name: "Austria", keywords: ["austria", "at"], category: "Flags", unicode: "U+1F1E6 U+1F1F9" },
  { emoji: "🇨🇿", name: "Czech Republic", keywords: ["czech", "cz"], category: "Flags", unicode: "U+1F1E8 U+1F1FF" },
  { emoji: "🇭🇺", name: "Hungary", keywords: ["hungary", "hu"], category: "Flags", unicode: "U+1F1ED U+1F1FA" },
  { emoji: "🇷🇴", name: "Romania", keywords: ["romania", "ro"], category: "Flags", unicode: "U+1F1F7 U+1F1F4" },
  { emoji: "🇧🇬", name: "Bulgaria", keywords: ["bulgaria", "bg"], category: "Flags", unicode: "U+1F1E7 U+1F1EC" },
  { emoji: "🇺🇦", name: "Ukraine", keywords: ["ukraine", "ua"], category: "Flags", unicode: "U+1F1FA U+1F1E6" },
  { emoji: "🇭🇷", name: "Croatia", keywords: ["croatia", "hr"], category: "Flags", unicode: "U+1F1ED U+1F1F7" },
  { emoji: "🇸🇮", name: "Slovenia", keywords: ["slovenia", "si"], category: "Flags", unicode: "U+1F1F8 U+1F1EE" },
  { emoji: "🇸🇰", name: "Slovakia", keywords: ["slovakia", "sk"], category: "Flags", unicode: "U+1F1F8 U+1F1F0" },
];
