import type { ReactNode } from "react";
import {
  Braces, Palette, DollarSign, Clock, Lock, Hash, FileText, Edit3,
  QrCode, GitCompare, Regex, BarChart3, Key, ShieldCheck, Globe, KeyRound,
  Type, Link2, ExternalLink, ArrowLeftRight, Ruler,
  Wrench, Code, Zap, Shield, Calculator, Receipt,
  Paintbrush, Square, Maximize2, Smile, Circle, ArrowUpDown,
  Dices, Timer, Scale, Percent, Server,
  Wallet, Mail, FileSpreadsheet, Database, Image, FileCode,
  Container, GitBranch, Tag, Sliders, Scissors, Sparkles, Eye,
  Keyboard, Replace, Terminal,
  TrendingUp, Target, Activity, BarChart2, LineChart, Coins, ArrowDownUp, Crosshair, Repeat
} from "lucide-react";

export type Category = "all" | "encoders" | "formatters" | "generators" | "converters" | "text" | "design" | "css" | "devtools" | "code" | "security" | "finance" | "calculators" | "data" | "trading";
export type Tool = {
  name: string;
  href: string;
  icon: ReactNode;
  description: string;
  color: string;
  category: Category;
  tags: string[];
};
export const categoryColors = {
  encoders: "from-blue-500 to-blue-600",         // Blue - Encode/decode
  formatters: "from-green-500 to-green-600",     // Green - Format code
  generators: "from-purple-500 to-purple-600",   // Purple - Generate data
  converters: "from-orange-500 to-orange-600",   // Orange - Convert formats
  text: "from-cyan-500 to-cyan-600",             // Cyan - Text manipulation
  design: "from-pink-500 to-pink-600",           // Pink - Design tools
  css: "from-fuchsia-500 to-fuchsia-600",        // Fuchsia - CSS tools
  devtools: "from-yellow-500 to-yellow-600",     // Yellow - Dev utilities
  code: "from-indigo-500 to-indigo-600",         // Indigo - Code generation
  security: "from-red-500 to-red-600",           // Red - Security tools
  finance: "from-emerald-500 to-emerald-600",    // Emerald - Finance calculators
  calculators: "from-teal-500 to-teal-600",      // Teal - Calculators
  data: "from-violet-500 to-violet-600",         // Violet - Data & API
  trading: "from-amber-500 to-yellow-600",       // Gold - Trading tools
};

export const tools: Tool[] = [
  // ENCODERS
  {
    name: "Base64",
    href: "/base64",
    icon: <Lock className="w-5 h-5" />,
    description: "Encode/decode Base64, URL, HTML",
    color: categoryColors.encoders,
    category: "encoders",
    tags: ["base64", "encode", "decode", "url"]},
  {
    name: "URL Parser",
    href: "/url-parse",
    icon: <ExternalLink className="w-5 h-5" />,
    description: "Parse URL components",
    color: categoryColors.encoders,
    category: "encoders",
    tags: ["url", "parse", "query", "params"]},
  {
    name: "MIME Type Lookup",
    href: "/mime",
    icon: <FileCode className="w-5 h-5" />,
    description: "Search file extensions and MIME types",
    color: categoryColors.devtools,
    category: "devtools",
    tags: ["mime", "file", "type", "extension", "web"]},
  {
    name: "JWT Decoder",
    href: "/jwt",
    icon: <KeyRound className="w-5 h-5" />,
    description: "Decode JSON Web Tokens",
    color: categoryColors.encoders,
    category: "encoders",
    tags: ["jwt", "token", "decode", "auth"]},
  // FORMATTERS
  {
    name: "JSON Formatter",
    href: "/json",
    icon: <Braces className="w-5 h-5" />,
    description: "Format, minify, and validate JSON",
    color: categoryColors.formatters,
    category: "formatters",
    tags: ["json", "format", "validate", "minify"]},
  {
    name: "CSS Formatter",
    href: "/css-format",
    icon: <Paintbrush className="w-5 h-5" />,
    description: "Format and beautify CSS code",
    color: categoryColors.formatters,
    category: "formatters",
    tags: ["css", "format", "beautify", "prettier", "code"]},
  {
    name: "HTML Formatter",
    href: "/html-format",
    icon: <Code className="w-5 h-5" />,
    description: "Format and beautify HTML",
    color: categoryColors.formatters,
    category: "formatters",
    tags: ["html", "format", "beautify", "indent", "code"]},
  {
    name: "XML Formatter",
    href: "/xml-format",
    icon: <Code className="w-5 h-5" />,
    description: "Format and beautify XML",
    color: categoryColors.formatters,
    category: "formatters",
    tags: ["xml", "format", "beautify", "indent", "code"]},
  {
    name: "SQL Formatter",
    href: "/sql-format",
    icon: <Database className="w-5 h-5" />,
    description: "Format and beautify SQL queries",
    color: categoryColors.formatters,
    category: "formatters",
    tags: ["sql", "format", "beautify", "database", "query"]},
  {
    name: "Markdown",
    href: "/markdown",
    icon: <Edit3 className="w-5 h-5" />,
    description: "Live markdown preview",
    color: categoryColors.formatters,
    category: "formatters",
    tags: ["markdown", "preview", "editor"]},
  { name: "JSON Repair", href: "/json-repair", icon: <Wrench className="w-5 h-5" />, description: "Fix broken JSON — missing quotes, trailing commas, unescaped characters", color: categoryColors.formatters, category: "formatters", tags: ["json repair", "fix json", "broken json", "json fixer", "json lint", "invalid json"]},
  { name: "JS Formatter", href: "/js-format", icon: <Code className="w-5 h-5" />, description: "Format and minify JavaScript", color: categoryColors.formatters, category: "formatters", tags: ["javascript", "formatter", "beautifier", "js", "format", "minify", "indent", "es6", "code"]},
  { name: "YAML Formatter", href: "/yaml", icon: <Braces className="w-5 h-5" />, description: "YAML formatter and validator", color: categoryColors.formatters, category: "formatters", tags: ["yaml", "format", "validate", "config"]},
  { name: "Code Formatter", href: "/code-formatter", icon: <Code className="w-5 h-5" />, description: "Multi-language code formatter", color: categoryColors.formatters, category: "formatters", tags: ["code", "format", "beautify", "html", "css", "javascript", "json", "sql"]},
  // GENERATORS
  {
    name: "Lorem Ipsum",
    href: "/lorem",
    icon: <FileText className="w-5 h-5" />,
    description: "Generate placeholder text",
    color: categoryColors.generators,
    category: "generators",
    tags: ["lorem", "ipsum", "placeholder", "text"]},
  {
    name: "QR Code",
    href: "/qr",
    icon: <QrCode className="w-5 h-5" />,
    description: "Generate QR codes",
    color: categoryColors.generators,
    category: "generators",
    tags: ["qr", "code", "generate", "barcode"]},
  {
    name: "Random Number",
    href: "/random",
    icon: <Dices className="w-5 h-5" />,
    description: "Generate random numbers",
    color: categoryColors.generators,
    category: "generators",
    tags: ["random", "number", "dice", "lottery"]},
  {
    name: "Color Palette",
    href: "/palette",
    icon: <Palette className="w-5 h-5" />,
    description: "Generate color palettes",
    color: categoryColors.generators,
    category: "generators",
    tags: ["color", "palette", "generate", "design"]},
  {
    name: "UUID Generator",
    href: "/uuid",
    icon: <Key className="w-5 h-5" />,
    description: "Generate random UUIDs",
    color: categoryColors.generators,
    category: "generators",
    tags: ["uuid", "guid", "random", "generate"]},
  { name: "Barcode Generator", href: "/barcode", icon: <BarChart3 className="w-5 h-5" />, description: "Generate Code 128, Code 39, EAN-13, EAN-8, and UPC-A barcodes", color: categoryColors.generators, category: "generators", tags: ["barcode", "code128", "code39", "ean13", "ean8", "upc", "scan", "product", "barcode generator"]},
  {
    name: "Nginx Config",
    href: "/nginx-gen",
    icon: <Server className="w-5 h-5" />,
    description: "Generate Nginx server block configurations",
    color: categoryColors.generators,
    category: "generators",
    tags: ["nginx", "config", "server", "reverse proxy", "ssl", "tls", "web server", "load balancer"]},
  // CONVERTERS
  {
    name: "CSV to JSON",
    href: "/csv-json",
    icon: <FileSpreadsheet className="w-5 h-5" />,
    description: "Convert CSV to JSON format",
    color: categoryColors.converters,
    category: "converters",
    tags: ["csv", "json", "convert", "spreadsheet", "data"]},
  {
    name: "Unit Converter",
    href: "/unit",
    icon: <Ruler className="w-5 h-5" />,
    description: "Length, weight, temp, data",
    color: categoryColors.converters,
    category: "converters",
    tags: ["unit", "length", "weight", "temperature", "convert"]},
  {
    name: "TOML to JSON",
    href: "/toml-json",
    icon: <FileCode className="w-5 h-5" />,
    description: "Convert TOML to JSON format",
    color: categoryColors.converters,
    category: "converters",
    tags: ["toml", "json", "convert", "config", "parser"]},
  {
    name: "HTML to MD",
    href: "/html-md",
    icon: <FileText className="w-5 h-5" />,
    description: "Convert HTML to Markdown",
    color: categoryColors.converters,
    category: "converters",
    tags: ["html", "markdown", "convert", "parser"]},
  {
    name: "Epoch Converter",
    href: "/epoch",
    icon: <Clock className="w-5 h-5" />,
    description: "Unix/Epoch timestamp converter",
    color: categoryColors.converters,
    category: "converters",
    tags: ["epoch", "unix", "timestamp", "date", "time", "convert"]},
  {
    name: "Currency Converter",
    href: "/currency",
    icon: <DollarSign className="w-5 h-5" />,
    description: "Convert currencies (offline rates)",
    color: categoryColors.converters,
    category: "converters",
    tags: ["currency", "money", "exchange", "forex", "convert"]},
  // TEXT TOOLS
  {
    name: "Case Converter",
    href: "/case",
    icon: <Type className="w-5 h-5" />,
    description: "Convert text case styles",
    color: categoryColors.text,
    category: "text",
    tags: ["case", "camel", "snake", "kebab", "pascal"]},
  {
    name: "Slug Generator",
    href: "/slug",
    icon: <Link2 className="w-5 h-5" />,
    description: "URL-friendly slugs",
    color: categoryColors.text,
    category: "text",
    tags: ["slug", "url", "seo", "permalink"]},
  {
    name: "Text Stats",
    href: "/text-stats",
    icon: <BarChart3 className="w-5 h-5" />,
    description: "Advanced text analysis & readability",
    color: categoryColors.text,
    category: "text",
    tags: ["text", "stats", "analysis", "readability", "flesch", "kincaid", "frequency", "statistics"]},
  {
    name: "Sort Lines",
    href: "/sort",
    icon: <ArrowUpDown className="w-5 h-5" />,
    description: "Sort text lines alphabetically",
    color: categoryColors.text,
    category: "text",
    tags: ["sort", "alphabetical", "order", "lines"]},
  {
    name: "Text Diff",
    href: "/diff",
    icon: <GitCompare className="w-5 h-5" />,
    description: "Compare text differences",
    color: categoryColors.text,
    category: "text",
    tags: ["diff", "compare", "text", "difference"]},
  {
    name: "Emoji Picker & Search",
    href: "/emoji",
    icon: <Smile className="w-5 h-5" />,
    description: "Browse & search 1800+ emojis with skin tones",
    color: categoryColors.text,
    category: "text",
    tags: ["emoji", "search", "picker", "unicode", "skin tone", "copy", "find"]},
  {
    name: "Extract Emails",
    href: "/extract-emails",
    icon: <Mail className="w-5 h-5" />,
    description: "Find emails in text",
    color: categoryColors.text,
    category: "text",
    tags: ["email", "extract", "find", "text"]},
  {
    name: "Text Replace",
    href: "/replace",
    icon: <Replace className="w-5 h-5" />,
    description: "Find and replace text with regex support",
    color: categoryColors.text,
    category: "text",
    tags: ["replace", "find", "regex", "text", "substitute"]},
  // DESIGN
  {
    name: "Color Converter",
    href: "/colors",
    icon: <Palette className="w-5 h-5" />,
    description: "Convert HEX, RGB, HSL colors",
    color: categoryColors.design,
    category: "design",
    tags: ["color", "hex", "rgb", "hsl", "convert"]},
  {
    name: "Font Pairing Suggestions",
    href: "/font-pairs",
    icon: <Type className="w-5 h-5" />,
    description: "Discover perfect Google Fonts pairings",
    color: categoryColors.design,
    category: "design",
    tags: ["font", "typography", "pairing", "google fonts", "design", "typeface", "heading", "body"]},
  {
    name: "Favicon Generator",
    href: "/favicon-gen",
    // eslint-disable-next-line jsx-a11y/alt-text
    icon: <Image className="w-5 h-5" />,
    description: "Generate favicon packages from images",
    color: categoryColors.design,
    category: "design",
    tags: ["favicon", "icon", "image", "png", "apple-touch-icon", "android", "manifest", "generator"]},
  {
    name: "Color Contrast Checker",
    href: "/contrast",
    icon: <Eye className="w-5 h-5" />,
    description: "WCAG accessibility contrast checker",
    color: categoryColors.design,
    category: "design",
    tags: ["contrast", "accessibility", "wcag", "aa", "aaa", "a11y", "color", "text", "readable"]},
  {
    name: "OG Image Generator",
    href: "/og-gen",
    // eslint-disable-next-line jsx-a11y/alt-text
    icon: <Image className="w-5 h-5" />,
    description: "Generate Open Graph images with templates",
    color: categoryColors.design,
    category: "design",
    tags: ["og", "opengraph", "social", "image", "template", "blog", "product", "announcement", "meta"]},
  {
    name: "Aspect Ratio Calculator",
    href: "/aspect-calc",
    icon: <Maximize2 className="w-5 h-5" />,
    description: "Calculate dimensions with locked ratios",
    color: categoryColors.design,
    category: "design",
    tags: ["aspect", "ratio", "dimensions", "resize", "scale", "video", "image", "preview"]},
  {
    name: "Color Picker",
    href: "/color-picker",
    icon: <Palette className="w-5 h-5" />,
    description: "Visual color picker with contrast checker",
    color: categoryColors.design,
    category: "design",
    tags: ["color", "picker", "eyedropper", "hex", "rgb", "hsl", "cmyk", "contrast", "wcag"]},
  // CSS TOOLS
  {
    name: "CSS Gradient",
    href: "/gradient",
    icon: <Paintbrush className="w-5 h-5" />,
    description: "Generate CSS gradients",
    color: categoryColors.css,
    category: "css",
    tags: ["gradient", "css", "color", "design"]},
  { name: "Advanced Gradient Generator", href: "/gradient-gen", icon: <Paintbrush className="w-5 h-5" />, description: "Advanced CSS gradient generator with radial and conic", color: categoryColors.css, category: "css", tags: ["gradient", "radial", "conic", "css", "design"]},
  {
    name: "Box Shadow",
    href: "/shadow",
    icon: <Square className="w-5 h-5" />,
    description: "CSS box shadow generator",
    color: categoryColors.css,
    category: "css",
    tags: ["shadow", "css", "box", "design"]},
  {
    name: "Border Radius",
    href: "/border",
    icon: <Circle className="w-5 h-5" />,
    description: "CSS border radius generator",
    color: categoryColors.css,
    category: "css",
    tags: ["border", "radius", "css", "rounded", "corners"]},
  {
    name: "CSS Animation Generator",
    href: "/css-animate",
    icon: <Sparkles className="w-5 h-5" />,
    description: "Visual keyframe animation builder",
    color: categoryColors.css,
    category: "css",
    tags: ["animation", "keyframes", "css", "animate", "transition", "transform", "visual", "timeline", "motion"]},
  {
    name: "CSS Clip-path",
    href: "/clip-path",
    icon: <Scissors className="w-5 h-5" />,
    description: "Visual clip-path shape editor",
    color: categoryColors.css,
    category: "css",
    tags: ["clip-path", "css", "shape", "polygon", "circle", "ellipse", "design", "visual", "editor"]},
  {
    name: "CSS Filter Generator",
    href: "/filter-gen",
    icon: <Sliders className="w-5 h-5" />,
    description: "Visual CSS filter effects editor",
    color: categoryColors.css,
    category: "css",
    tags: ["filter", "css", "blur", "brightness", "contrast", "grayscale", "saturate", "sepia", "hue", "visual", "effects"]},
  // SECURITY
  {
    name: "Hash Generator",
    href: "/hash",
    icon: <Hash className="w-5 h-5" />,
    description: "MD5, SHA-1, SHA-256, SHA-512",
    color: categoryColors.security,
    category: "security",
    tags: ["hash", "md5", "sha", "checksum"]},
  {
    name: "TOTP Generator",
    href: "/totp",
    icon: <Shield className="w-5 h-5" />,
    description: "Time-based one-time passwords",
    color: categoryColors.security,
    category: "security",
    tags: ["totp", "otp", "2fa", "authenticator", "security", "hmac"]},
  {
    name: "HMAC Generator",
    href: "/hmac",
    icon: <ShieldCheck className="w-5 h-5" />,
    description: "Generate HMAC signatures (SHA-256, SHA-512)",
    color: categoryColors.security,
    category: "security",
    tags: ["hmac", "signature", "sha256", "sha512", "api", "auth"]},
  {
    name: "Bcrypt Hash",
    href: "/bcrypt",
    icon: <Lock className="w-5 h-5" />,
    description: "Bcrypt password hashing and verification",
    color: categoryColors.security,
    category: "security",
    tags: ["bcrypt", "password", "hash", "security", "verify"]},
  {
    name: "Encrypt/Decrypt",
    href: "/encrypt",
    icon: <Lock className="w-5 h-5" />,
    description: "AES encryption and decryption",
    color: categoryColors.security,
    category: "security",
    tags: ["encrypt", "decrypt", "aes", "cipher", "security"]},
  {
    name: "Certificate Decoder",
    href: "/cert-decoder",
    icon: <Shield className="w-5 h-5" />,
    description: "Decode SSL/TLS X.509 certificates",
    color: categoryColors.security,
    category: "security",
    tags: ["certificate", "ssl", "tls", "x509", "pem", "security", "decode"]},
  {
    name: "Password",
    href: "/password",
    icon: <ShieldCheck className="w-5 h-5" />,
    description: "Secure password generator",
    color: categoryColors.security,
    category: "security",
    tags: ["password", "secure", "random", "generate"]},
  {
    name: "SSH Key Generator",
    href: "/ssh-keygen",
    icon: <Key className="w-5 h-5" />,
    description: "Generate RSA & Ed25519 SSH key pairs in browser",
    color: categoryColors.security,
    category: "security",
    tags: ["ssh", "key", "rsa", "ed25519", "keygen", "crypto", "public key", "private key"]},
  // DEV UTILITIES
  {
    name: "Regex Tester",
    href: "/regex",
    icon: <Regex className="w-5 h-5" />,
    description: "Test regular expressions",
    color: categoryColors.devtools,
    category: "devtools",
    tags: ["regex", "regexp", "test", "match"]},
  {
    name: "CIDR Calculator",
    href: "/cidr",
    icon: <Globe className="w-5 h-5" />,
    description: "Calculate IP subnet information",
    color: categoryColors.devtools,
    category: "devtools",
    tags: ["cidr", "subnet", "ip", "network", "calculator", "netmask", "wildcard", "ipv4", "hosts"]},
  {
    name: "HTTP Status Codes",
    href: "/http-codes",
    icon: <Server className="w-5 h-5" />,
    description: "HTTP status code reference",
    color: categoryColors.devtools,
    category: "devtools",
    tags: ["http", "status", "codes", "api", "reference"]},
  {
    name: "Cron Parser",
    href: "/cron",
    icon: <Clock className="w-5 h-5" />,
    description: "Parse cron expressions & next runs",
    color: categoryColors.devtools,
    category: "devtools",
    tags: ["cron", "schedule", "expression", "job", "parser", "next", "execution"]},
  {
    name: "My IP",
    href: "/ip",
    icon: <Globe className="w-5 h-5" />,
    description: "Your public IP & location",
    color: categoryColors.devtools,
    category: "devtools",
    tags: ["ip", "address", "location", "network"]},
  {
    name: "Pomodoro Timer",
    href: "/pomodoro",
    icon: <Timer className="w-5 h-5" />,
    description: "Focus timer with breaks",
    color: categoryColors.devtools,
    category: "devtools",
    tags: ["pomodoro", "timer", "focus", "productivity"]},
  {
    name: "JavaScript KeyCode",
    href: "/keycode",
    icon: <Keyboard className="w-5 h-5" />,
    description: "Interactive keyboard event tester",
    color: categoryColors.devtools,
    category: "devtools",
    tags: ["keycode", "keyboard", "event", "javascript", "key", "code"]},
  {
    name: "chmod Calculator",
    href: "/chmod-calc",
    icon: <Lock className="w-5 h-5" />,
    description: "Advanced Unix permissions calculator",
    color: categoryColors.devtools,
    category: "devtools",
    tags: ["chmod", "permissions", "unix", "linux", "octal", "symbolic"]},
  {
    name: "DNS Lookup",
    href: "/dns-lookup",
    icon: <Globe className="w-5 h-5" />,
    description: "Query DNS records via DNS-over-HTTPS",
    color: categoryColors.devtools,
    category: "devtools",
    tags: ["dns", "lookup", "a", "aaaa", "mx", "txt", "ns", "cname", "soa", "ptr", "query"]},
  {
    name: "cURL Builder",
    href: "/curl-builder",
    icon: <Terminal className="w-5 h-5" />,
    description: "Build cURL commands visually with headers, auth & body",
    color: categoryColors.devtools,
    category: "devtools",
    tags: ["curl", "http", "api", "request", "builder", "rest", "headers", "auth", "post", "get"]},
  { name: "Email Validator", href: "/email-validator", icon: <Mail className="w-5 h-5" />, description: "Validate email addresses with syntax checking and disposable detection", color: categoryColors.devtools, category: "devtools", tags: ["email validator", "validate email", "email checker", "email syntax", "disposable email", "email format"]},
  { name: "Semver Calculator", href: "/semver", icon: <Tag className="w-5 h-5" />, description: "Parse, compare, and validate semantic versions", color: categoryColors.devtools, category: "devtools", tags: ["semver", "semantic", "version", "compare", "validate", "npm"]},
  { name: "Token Counter", href: "/token-counter", icon: <Hash className="w-5 h-5" />, description: "Count AI tokens for GPT, Claude, and other models", color: categoryColors.devtools, category: "devtools", tags: ["token", "counter", "ai", "gpt", "claude", "tiktoken", "llm"]},
  // CODE TOOLS
  {
    name: "Docker Compose Builder",
    href: "/docker",
    icon: <Container className="w-5 h-5" />,
    description: "Generate docker-compose.yml files",
    color: categoryColors.code,
    category: "code",
    tags: ["docker", "compose", "container", "yaml", "devops", "nginx", "mysql", "postgres", "redis", "mongodb"]},
  {
    name: ".gitignore Generator",
    href: "/gitignore",
    icon: <GitBranch className="w-5 h-5" />,
    description: "Generate .gitignore for your projects",
    color: categoryColors.code,
    category: "code",
    tags: ["gitignore", "git", "ignore", "node", "python", "java", "go", "rust", "vscode", "jetbrains"]},
  {
    name: "Meta Tags Generator",
    href: "/meta-gen",
    icon: <Tag className="w-5 h-5" />,
    description: "Advanced SEO meta tags with live previews",
    color: categoryColors.code,
    category: "code",
    tags: ["meta", "seo", "og", "opengraph", "twitter", "card", "tags", "html", "canonical", "preview"]},
  {
    name: "JSON to TypeScript",
    href: "/json-to-ts",
    icon: <Code className="w-5 h-5" />,
    description: "Generate TypeScript types from JSON",
    color: categoryColors.code,
    category: "code",
    tags: ["json", "typescript", "types", "interface", "convert", "generator", "ts"]},
  {
    name: "JSON Schema Generator",
    href: "/json-schema",
    icon: <FileCode className="w-5 h-5" />,
    description: "Generate JSON Schema from any JSON object",
    color: categoryColors.code,
    category: "code",
    tags: ["json", "schema", "validate", "api", "draft-07", "2020-12", "generator"]},
  {
    name: "SVG Optimizer",
    href: "/svg-optimize",
    icon: <FileCode className="w-5 h-5" />,
    description: "Optimize and minify SVG files",
    color: categoryColors.code,
    category: "code",
    tags: ["svg", "optimize", "minify", "clean", "size"]},
  // DATA & API
  {
    name: "HTML Entities",
    href: "/html-entities",
    icon: <Code className="w-5 h-5" />,
    description: "Encode/decode HTML entities with reference",
    color: categoryColors.data,
    category: "data",
    tags: ["html", "entities", "encode", "decode", "escape", "unescape", "special", "characters"]},
  {
    name: "JSON Path Finder",
    href: "/json-path",
    icon: <Braces className="w-5 h-5" />,
    description: "Visual JSON explorer with path extraction",
    color: categoryColors.data,
    category: "data",
    tags: ["json", "path", "explorer", "tree", "navigate", "jsonpath", "dot", "bracket", "finder"]},
  {
    name: "Mock API",
    href: "/mock-api",
    icon: <Database className="w-5 h-5" />,
    description: "Generate mock API responses",
    color: categoryColors.data,
    category: "data",
    tags: ["api", "mock", "json", "data", "generator", "testing"]},
  { name: "Webhook Tester", href: "/webhook-tester", icon: <Globe className="w-5 h-5" />, description: "Generate webhook URLs and inspect incoming HTTP requests in real-time", color: categoryColors.data, category: "data", tags: ["webhook", "webhook tester", "http request", "api test", "inspect", "endpoint"]},
  { name: "OpenAPI Validator", href: "/openapi-validator", icon: <FileCode className="w-5 h-5" />, description: "Validate OpenAPI/Swagger specifications (v2 and v3) with detailed error reports", color: categoryColors.data, category: "data", tags: ["openapi", "swagger", "validator", "api spec", "openapi validator", "rest api", "schema"]},
  // FINANCE
  {
    name: "Tip Calculator",
    href: "/tip",
    icon: <Receipt className="w-5 h-5" />,
    description: "Calculate tips & split bills",
    color: categoryColors.finance,
    category: "finance",
    tags: ["tip", "bill", "split", "restaurant"]},
  {
    name: "VAT Calculator",
    href: "/vat",
    icon: <Receipt className="w-5 h-5" />,
    description: "Add or remove VAT/tax",
    color: categoryColors.finance,
    category: "finance",
    tags: ["vat", "tax", "calculator", "gst"]},
  {
    name: "Fee Calculator",
    href: "/fees",
    icon: <DollarSign className="w-5 h-5" />,
    description: "PayPal, Stripe, Wise fees",
    color: categoryColors.finance,
    category: "finance",
    tags: ["paypal", "stripe", "wise", "fee", "calculator"]},
  {
    name: "Discount",
    href: "/discount",
    icon: <Percent className="w-5 h-5" />,
    description: "Calculate discounts & savings",
    color: categoryColors.finance,
    category: "finance",
    tags: ["discount", "sale", "savings", "calculator"]},
  {
    name: "Loan Calculator",
    href: "/loan",
    icon: <Wallet className="w-5 h-5" />,
    description: "Calculate monthly payments",
    color: categoryColors.finance,
    category: "finance",
    tags: ["loan", "mortgage", "payment", "interest"]},
  {
    name: "Percentage",
    href: "/percentage",
    icon: <Calculator className="w-5 h-5" />,
    description: "Percentage calculations",
    color: categoryColors.finance,
    category: "finance",
    tags: ["percentage", "percent", "calculate", "math"]},
  // CALCULATORS
  { name: "Math Evaluator", href: "/math-eval", icon: <Calculator className="w-5 h-5" />, description: "Evaluate mathematical expressions", color: categoryColors.calculators, category: "calculators", tags: ["math", "calculator", "evaluate", "expression", "formula"]},
  // TRADING
  { name: "Position Size Calculator", href: "/position-size", icon: <Target className="w-5 h-5" />, description: "Calculate optimal position size from risk parameters", color: categoryColors.trading, category: "trading", tags: ["position size", "risk management", "trading", "forex", "stocks", "lot size", "stop loss"]},
  { name: "Risk/Reward Calculator", href: "/risk-reward", icon: <Activity className="w-5 h-5" />, description: "Calculate risk/reward ratio and breakeven win rate", color: categoryColors.trading, category: "trading", tags: ["risk reward", "ratio", "trading", "entry", "stop loss", "take profit", "breakeven"]},
  { name: "Fibonacci Retracement", href: "/fibonacci-trading", icon: <TrendingUp className="w-5 h-5" />, description: "Calculate Fibonacci retracement and extension levels", color: categoryColors.trading, category: "trading", tags: ["fibonacci", "retracement", "extension", "trading", "technical analysis", "support", "resistance"]},
  { name: "Pivot Points Calculator", href: "/pivot-points", icon: <Crosshair className="w-5 h-5" />, description: "Calculate pivot points from OHLC data", color: categoryColors.trading, category: "trading", tags: ["pivot points", "support", "resistance", "OHLC", "trading", "standard", "fibonacci", "camarilla"]},
  { name: "Drawdown Calculator", href: "/drawdown-calc", icon: <ArrowDownUp className="w-5 h-5" />, description: "Calculate drawdown recovery and scenario analysis", color: categoryColors.trading, category: "trading", tags: ["drawdown", "recovery", "trading", "risk", "loss", "portfolio", "max drawdown"]},
  { name: "Kelly Criterion", href: "/kelly-criterion", icon: <BarChart2 className="w-5 h-5" />, description: "Calculate optimal bet sizing with Kelly formula", color: categoryColors.trading, category: "trading", tags: ["kelly criterion", "bet sizing", "optimal", "trading", "risk management", "win rate"]},
  { name: "Compound Growth", href: "/compound-growth", icon: <LineChart className="w-5 h-5" />, description: "Project compound growth with interactive chart", color: categoryColors.trading, category: "trading", tags: ["compound growth", "interest", "projection", "trading", "investment", "returns", "chart"]},
  { name: "Pip Value Calculator", href: "/pip-value", icon: <Coins className="w-5 h-5" />, description: "Calculate pip value for forex currency pairs", color: categoryColors.trading, category: "trading", tags: ["pip value", "forex", "currency", "lot size", "trading", "pips", "pairs"]},
  { name: "Margin Calculator", href: "/margin-calc", icon: <Scale className="w-5 h-5" />, description: "Calculate margin requirements and liquidation price", color: categoryColors.trading, category: "trading", tags: ["margin", "leverage", "liquidation", "trading", "futures", "margin call", "collateral"]},
  { name: "DCA Calculator", href: "/dca-calc", icon: <Repeat className="w-5 h-5" />, description: "Dollar-cost averaging calculator with breakeven analysis", color: categoryColors.trading, category: "trading", tags: ["dca", "dollar cost averaging", "average price", "trading", "investment", "crypto", "stocks"]},
];

export const categories: { id: Category; name: string; icon: ReactNode; color: string; description: string }[] = [
  { id: "all", name: "All Tools", icon: <Wrench className="w-4 h-4" />, color: "from-zinc-500 to-zinc-600", description: "Browse all available tools" },
  { id: "encoders", name: "Encoders", icon: <Lock className="w-4 h-4" />, color: categoryColors.encoders, description: "Encode, decode, and transform data" },
  { id: "formatters", name: "Formatters", icon: <Braces className="w-4 h-4" />, color: categoryColors.formatters, description: "Format and beautify code" },
  { id: "generators", name: "Generators", icon: <Zap className="w-4 h-4" />, color: categoryColors.generators, description: "Generate random data and content" },
  { id: "converters", name: "Converters", icon: <ArrowLeftRight className="w-4 h-4" />, color: categoryColors.converters, description: "Convert between formats and units" },
  { id: "text", name: "Text Tools", icon: <Type className="w-4 h-4" />, color: categoryColors.text, description: "Manipulate and analyze text" },
  { id: "design", name: "Design", icon: <Palette className="w-4 h-4" />, color: categoryColors.design, description: "Color tools and design utilities" },
  { id: "css", name: "CSS Tools", icon: <Paintbrush className="w-4 h-4" />, color: categoryColors.css, description: "CSS generators and visual editors" },
  { id: "devtools", name: "Dev Utilities", icon: <Code className="w-4 h-4" />, color: categoryColors.devtools, description: "Developer tools and utilities" },
  { id: "code", name: "Code Tools", icon: <FileCode className="w-4 h-4" />, color: categoryColors.code, description: "Code generation and conversion" },
  { id: "security", name: "Security", icon: <Shield className="w-4 h-4" />, color: categoryColors.security, description: "Security and cryptography tools" },
  { id: "finance", name: "Finance", icon: <DollarSign className="w-4 h-4" />, color: categoryColors.finance, description: "Financial calculators and tools" },
  { id: "data", name: "Data & API", icon: <Database className="w-4 h-4" />, color: categoryColors.data, description: "Data manipulation and API tools" },
  { id: "trading", name: "Trading", icon: <TrendingUp className="w-4 h-4" />, color: categoryColors.trading, description: "Trading calculators and analysis tools" },
];
