/**
 * JWT Decoder Tool Guide Content
 * Comprehensive developer guide for JWT token decoding and analysis
 */

import type { ToolGuideContent } from "./types";

export const jwtGuideContent: ToolGuideContent = {
  toolName: "JWT Decoder",
  toolPath: "/jwt",
  lastUpdated: "2026-02-01",
  version: "2.0",

  quickStartSteps: [
    {
      title: "Paste JWT Token",
      description: "Copy and paste a complete JWT token (including header.payload.signature) from HTTP headers, API responses, cookies, or authentication systems. The tool automatically validates the JWT structure."
    },
    {
      title: "View Decoded Sections",
      description: "Instantly see decoded header (algorithm and token type), payload (claims and data), and signature. All three JWT components are Base64-decoded and formatted as readable JSON."
    },
    {
      title: "Inspect Claims and Metadata",
      description: "Review standard claims (iss, sub, aud, exp, iat) and custom claims. Check token expiration, issued time, and audience. Validate claim structure matches API specifications."
    },
    {
      title: "Verify Token Integrity",
      description: "The tool validates JWT format and structure but does NOT verify cryptographic signatures. Use for debugging and inspection only - never for production security validation."
    }
  ],

  introduction: {
    title: "What is a JWT Decoder?",
    content: `A JWT (JSON Web Token) decoder is a development tool that decodes and displays the contents of JWT tokens used for authentication and authorization in modern web applications. JWTs are compact, URL-safe tokens that encode JSON data in three Base64-encoded sections: header, payload, and signature. A JWT decoder parses these sections, revealing the token's algorithm, claims, expiration, and other metadata essential for debugging authentication flows.

JWT tokens are the de facto standard for stateless authentication in REST APIs, OAuth 2.0, OpenID Connect (OIDC), and single sign-on (SSO) systems. Developers encounter JWTs daily when working with authentication, API security, microservices, and third-party integrations. Understanding JWT structure and claims is critical for debugging auth issues, implementing security correctly, and integrating with identity providers.

### JWT Token Structure

A JWT consists of three Base64 URL-encoded sections separated by dots (.): **header.payload.signature**

**Header:** Contains token type (typ: "JWT") and signing algorithm (alg: "HS256", "RS256", etc.). The algorithm specifies how the signature is generated and verified. Common algorithms: HS256 (HMAC SHA-256), RS256 (RSA SHA-256), ES256 (ECDSA SHA-256).

**Payload:** Contains claims - JSON key-value pairs with user data, permissions, and metadata. Standard claims include iss (issuer), sub (subject/user ID), aud (audience), exp (expiration time), iat (issued at time), and nbf (not before time). Custom claims can include user roles, permissions, or any application-specific data.

**Signature:** Cryptographic signature that validates the token hasn't been tampered with. Generated by signing the header and payload with a secret key (HS256) or private key (RS256). Only systems with the secret/public key can verify the signature. The signature ensures token integrity and authenticity.

### Why Developers Need JWT Decoders

Debugging authentication flows requires inspecting JWT contents to verify claims are correct. Common issues: expired tokens (exp claim in the past), wrong audience (aud doesn't match API), missing permissions (custom role claims incorrect), or algorithm mismatches (API expects RS256 but receives HS256).

API integration with identity providers (Auth0, Okta, AWS Cognito, Firebase Auth) involves validating JWT structure matches specifications. JWT decoders help verify tokens contain expected claims, use correct algorithms, and follow provider documentation.

Security analysis requires examining JWT tokens for vulnerabilities: weak algorithms (none, HS256 with weak secrets), overly permissive claims (admin roles for regular users), excessive token lifetimes (exp too far in future), or sensitive data exposure (personal information in payload).

Development and testing workflows use JWT decoders to inspect tokens during development, verify token generation logic produces correct claims, and troubleshoot authentication errors in development or staging environments.

### JWT vs Other Token Formats

Unlike opaque tokens (random strings requiring database lookup), JWTs are self-contained - all data is in the token. This enables stateless authentication where servers validate tokens without database queries, improving scalability and performance.

Session IDs stored in cookies require server-side session storage. JWTs can be stored client-side (localStorage, cookies) and validated without server state. This makes JWTs ideal for distributed systems and microservices.

API keys are static and permanent. JWTs are temporary (with exp claim) and can include dynamic claims (user permissions that change). JWTs support fine-grained authorization through custom claims.

### Common JWT Use Cases

**Authentication:** After login, server generates JWT with user ID and roles. Client includes JWT in Authorization header for subsequent API requests. Server validates JWT signature and checks claims to authenticate and authorize requests.

**Single Sign-On (SSO):** User logs into identity provider, receives JWT. Multiple applications trust the same JWT for authentication. OIDC ID tokens are JWTs containing user profile information.

**API Security:** Microservices validate JWTs to authenticate requests without querying a central auth database. JWT claims include permissions for fine-grained access control.

**Information Exchange:** JWTs securely transmit information between parties. The signature ensures the data hasn't been tampered with. Used for sharing user profile data, permissions, or session information.

### CRITICAL: Client-Side Decoding Limitations

**NEVER use client-side JWT decoding for production security validation.** This tool decodes and displays JWT contents but does NOT verify cryptographic signatures. Anyone can create a JWT with fake claims - only signature verification proves authenticity.

In production, always verify JWT signatures on the server using proper cryptographic libraries (jsonwebtoken in Node.js, PyJWT in Python, jose in Go). Client-side decoding is for debugging and development only, never for security decisions.

Storing JWTs in localStorage exposes them to XSS attacks. Prefer httpOnly cookies for production. Never store sensitive secrets in JWT payloads - they're Base64-encoded (readable by anyone), not encrypted.`,
  },

  useCases: [
    {
      title: "Authentication Debugging and Troubleshooting",
      description: "Debug failed authentication by decoding JWTs to verify claims are correct. Check token expiration, validate issuer and audience, ensure required claims are present. Essential for troubleshooting 401 Unauthorized and 403 Forbidden errors.",
      example: `// Debugging 401 Unauthorized error
// API returns: "Invalid token"

// 1. Copy JWT from Authorization header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzkwMjJ9.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

// 2. Decode with this tool
// Header:
{
  "alg": "HS256",
  "typ": "JWT"
}

// Payload:
{
  "sub": "1234567890",
  "name": "John Doe",
  "iat": 1516239022,
  "exp": 1516239022  // ⚠️ EXPIRED!
}

// 3. Problem identified: exp (expiration) = iat (issued at)
// Token expired immediately after creation
// Solution: Fix token generation to set exp in future

// Common debugging scenarios:
// ❌ exp in the past → Token expired
// ❌ aud doesn't match API → Wrong audience
// ❌ iss doesn't match expected issuer → Wrong token source
// ❌ Missing required claims (sub, roles) → Incomplete token
// ❌ Algorithm mismatch (HS256 vs RS256) → Verification fails`
    },
    {
      title: "OAuth 2.0 and OIDC Integration",
      description: "Integrate with identity providers (Auth0, Okta, AWS Cognito, Google, Microsoft) by decoding their JWT ID tokens and access tokens. Verify token structure matches provider documentation and contains expected claims for user authentication.",
      example: `// OIDC ID Token from Auth0
// After successful OAuth login:

// Decoded ID Token:
// Header:
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "abc123"  // Key ID for signature verification
}

// Payload (OIDC standard claims):
{
  "iss": "https://YOUR_DOMAIN.auth0.com/",
  "sub": "auth0|507f1f77bcf86cd799439011",
  "aud": "YOUR_CLIENT_ID",
  "exp": 1709251200,  // Expiration: 2026-03-01
  "iat": 1709247600,  // Issued: 2026-02-28
  "nonce": "abc123",
  "email": "john@example.com",
  "email_verified": true,
  "name": "John Doe",
  "picture": "https://example.com/photo.jpg"
}

// Validation checklist:
// ✅ iss matches your Auth0 domain
// ✅ aud matches your application client ID
// ✅ exp is in the future (not expired)
// ✅ email_verified is true (if required)
// ✅ Contains required custom claims (roles, permissions)

// Access Token (for API authorization):
{
  "iss": "https://YOUR_DOMAIN.auth0.com/",
  "sub": "auth0|507f1f77bcf86cd799439011",
  "aud": ["https://api.example.com"],
  "scope": "read:users write:users",
  "permissions": ["admin", "editor"]
}

// Use decoded claims to:
// 1. Display user profile (name, email, picture)
// 2. Check permissions for UI elements
// 3. Validate token before API calls
// 4. Debug integration issues`
    },
    {
      title: "Microservices Authentication Validation",
      description: "Validate JWTs in microservices architectures where multiple services verify tokens independently. Decode tokens to ensure they contain required claims for service-to-service communication and user authorization across distributed systems.",
      example: `// Microservices JWT validation workflow
// Service A (API Gateway) receives request with JWT
// Service B (User Service) validates same JWT

// Decoded JWT for microservices:
// Header:
{
  "alg": "RS256",  // Asymmetric - services verify with public key
  "typ": "JWT"
}

// Payload:
{
  "iss": "auth-service.example.com",
  "sub": "user_12345",
  "aud": ["api.example.com", "users.example.com"],  // Multiple audiences
  "exp": 1709251200,
  "iat": 1709247600,
  "scope": "api:read api:write",
  "roles": ["user", "premium"],
  "tenant_id": "org_abc123",
  "service_permissions": {
    "user_service": ["read", "update"],
    "payment_service": ["read"],
    "admin_service": []  // No access
  }
}

// Service validation logic:
// 1. Verify signature with public key (RS256)
// 2. Check exp > current time
// 3. Verify aud includes service audience
// 4. Extract service_permissions for authorization
// 5. Use sub (user ID) for data filtering

// Debugging service-to-service auth:
// ❌ aud missing service URL → Token not valid for this service
// ❌ service_permissions missing key → Insufficient access
// ❌ tenant_id doesn't match → Multi-tenant isolation issue
// ✅ All claims present and valid → Auth successful`
    },
    {
      title: "Security Audit and Vulnerability Analysis",
      description: "Audit JWT implementations for security vulnerabilities: weak algorithms, excessive token lifetimes, sensitive data exposure, or missing security claims. Essential for security reviews, penetration testing, and compliance audits.",
      example: `// Security audit checklist using JWT decoder

// ⚠️ VULNERABLE TOKEN EXAMPLE:
{
  "alg": "none",  // ❌ CRITICAL: No signature!
  "typ": "JWT"
}
{
  "sub": "user123",
  "role": "admin",  // ⚠️ Anyone can create this!
  "exp": 9999999999  // ❌ Expires year 2286 (too long)
}

// Security issues identified:
// 1. Algorithm "none" = no signature verification
//    Fix: Use HS256, RS256, or ES256
// 2. Excessive token lifetime (decades)
//    Fix: Set exp to 15min-1hr, use refresh tokens
// 3. No aud (audience) claim
//    Fix: Add aud to prevent token reuse across services

// ⚠️ SENSITIVE DATA EXPOSURE:
{
  "sub": "user123",
  "email": "john@example.com",
  "ssn": "123-45-6789",  // ❌ PII in JWT!
  "credit_card": "4111111111111111",  // ❌ Payment data!
  "password_hash": "$2b$10$..."  // ❌ Credentials!
}
// Fix: Never store PII, payment data, or credentials in JWTs
// JWTs are Base64-encoded (readable), not encrypted

// ✅ SECURE TOKEN EXAMPLE:
{
  "alg": "RS256",  // ✅ Strong asymmetric algorithm
  "typ": "JWT",
  "kid": "key123"  // ✅ Key ID for rotation
}
{
  "iss": "https://auth.example.com",
  "sub": "user_uuid_abc123",  // ✅ Opaque user ID
  "aud": "https://api.example.com",  // ✅ Specific audience
  "exp": 1709248500,  // ✅ 15 minute expiration
  "iat": 1709247600,
  "nbf": 1709247600,  // ✅ Not before (prevent replay)
  "jti": "unique_token_id_xyz",  // ✅ Token ID (revocation)
  "scope": "read:profile",  // ✅ Limited permissions
  "tenant": "org_abc"  // ✅ Multi-tenant isolation
}

// Security best practices:
// ✅ Use RS256/ES256 (asymmetric) for distributed systems
// ✅ Short expiration (15min-1hr), use refresh tokens
// ✅ Include aud, iss, jti for validation and revocation
// ✅ Store minimal data (user ID, roles), never PII
// ✅ Use httpOnly cookies, not localStorage (XSS protection)`
    }
  ],

  howToUse: {
    title: "How to Use This JWT Decoder Tool",
    content: `This JWT decoder parses and displays all three sections of JWT tokens with real-time validation and formatted JSON output. All processing happens client-side - your tokens never leave your browser.

### Decoding a JWT Token

Paste a complete JWT token (including all three sections: header.payload.signature) into the input field. The tool automatically detects the JWT format and decodes each section instantly. Results appear as formatted JSON for easy reading.

JWT tokens typically start with "eyJ" (Base64 encoding of {"alg":...). If your token doesn't start this way, verify it's a valid JWT and not a different token format (opaque token, session ID, API key).

The three sections are separated by dots (.). All three must be present for valid JWT structure, though the signature section may be empty for unsigned tokens (alg: "none", which is insecure).

### Understanding Decoded Sections

**Header:** Shows the signing algorithm (alg) and token type (typ). Common algorithms: HS256 (symmetric HMAC), RS256 (asymmetric RSA), ES256 (asymmetric ECDSA). The kid (key ID) field indicates which key was used for signing, enabling key rotation.

**Payload:** Contains claims - the actual data in the token. Standard claims follow IETF RFC 7519 specification: iss (issuer), sub (subject), aud (audience), exp (expiration), iat (issued at), nbf (not before), jti (JWT ID). Custom claims can include user roles, permissions, tenant IDs, or any application-specific data.

**Signature:** Displayed as Base64-encoded string. The signature cannot be meaningfully decoded - it's a cryptographic hash. Signature verification requires the secret key (HS256) or public key (RS256) and happens on the server, not in this tool.

### Checking Token Expiration

The exp (expiration) claim is a Unix timestamp (seconds since Jan 1, 1970). The tool converts this to human-readable date/time. If exp is in the past, the token is expired and should be rejected by APIs.

Compare exp to current time. Expired tokens cause 401 Unauthorized errors. Check iat (issued at) and exp difference to see token lifetime. Typical lifetimes: 15 minutes (access tokens), 7 days (refresh tokens), 1 hour (ID tokens).

The nbf (not before) claim indicates when the token becomes valid. If nbf is in the future, the token is not yet valid. This prevents clock skew issues in distributed systems.

### Validating Claims

**iss (issuer):** Should match your identity provider's URL. Mismatch indicates token from wrong source or forgery attempt.

**aud (audience):** Should match your API or application identifier. Prevents tokens issued for one API being used on another.

**sub (subject):** User identifier (UUID, email, username). Use this to identify the authenticated user.

**scope or permissions:** Custom claims for authorization. Check these match expected user permissions.

### CRITICAL SECURITY WARNING

**This tool decodes JWTs but does NOT verify signatures.** Anyone can create a JWT with fake claims. Only cryptographic signature verification proves a token is authentic and hasn't been tampered with.

**NEVER use client-side JWT decoding for production authentication or authorization decisions.** Always verify signatures on the server using proper cryptographic libraries:
- Node.js: jsonwebtoken, jose
- Python: PyJWT, python-jose
- Go: golang-jwt/jwt, go-jose
- Java: java-jwt, nimbus-jose-jwt

**Never store sensitive data in JWT payloads.** JWTs are Base64-encoded (easily readable), not encrypted. Anyone with access to the token can decode and read the payload. Store only minimal data: user ID, roles, permissions. Never include passwords, API keys, PII (social security numbers, credit cards), or confidential data.

### Common JWT Errors

**Invalid signature:** Server rejects token because signature doesn't match. Check algorithm (HS256 vs RS256), verify correct secret/public key is used, ensure header and payload weren't modified.

**Token expired:** exp claim is in the past. Refresh the token or re-authenticate the user.

**Invalid audience:** aud claim doesn't match API's expected audience. Token was issued for a different application or service.

**Algorithm mismatch:** API expects RS256 but receives HS256 (or vice versa). Align token generation and validation algorithms.

**Malformed token:** Missing sections (not 3 parts separated by dots), invalid Base64 encoding, or corrupted during transmission.

### Keyboard Shortcuts

- **Ctrl+V / Cmd+V:** Paste JWT token
- **Ctrl+C / Cmd+C:** Copy decoded JSON
- **Ctrl+K / Cmd+K:** Clear input and output

### Working with Different JWT Sources

**HTTP Authorization Header:** Remove "Bearer " prefix before pasting. Only paste the token itself: eyJhbGciOi...

**Cookies:** Extract JWT value from browser DevTools → Application → Cookies. Look for cookies named "token", "auth_token", "jwt", or similar.

**API Responses:** After login, APIs return tokens in response body: {"token": "eyJ..."}. Copy just the token value.

**Browser Storage:** Open DevTools → Application → Local Storage or Session Storage. Look for JWT tokens stored by the application.`,
    steps: [
      {
        name: "Copy JWT Token",
        text: "Copy the complete JWT token from Authorization headers, API responses, cookies, or browser storage. Include all three sections (header.payload.signature)."
      },
      {
        name: "Paste and Decode",
        text: "Paste the JWT into the input field. The tool automatically validates structure and decodes all three sections as formatted JSON."
      },
      {
        name: "Inspect Claims",
        text: "Review decoded header (algorithm, type), payload (claims, expiration), and signature. Verify standard claims (iss, sub, aud, exp) and custom claims match expectations."
      },
      {
        name: "Debug Issues",
        text: "Check for expired tokens (exp in past), wrong audience (aud mismatch), missing claims, or algorithm issues. Use findings to fix authentication problems."
      }
    ]
  },

  faqs: [
    {
      question: "Does this tool verify JWT signatures?",
      answer: "No. This tool decodes and displays JWT contents but does NOT verify cryptographic signatures. Signature verification requires the secret key (HS256) or public key (RS256) and must happen on the server using proper cryptographic libraries. Client-side decoding is for debugging only, never for production security validation. Anyone can create a JWT with fake claims - only signature verification proves authenticity."
    },
    {
      question: "Is it safe to paste JWTs into this tool?",
      answer: "Yes for debugging, no for production secrets. All decoding happens client-side in your browser - tokens never leave your device. However, never paste production JWTs containing real user data into any tool on shared/public computers. For production debugging, use local tools or your own JWT decoder. This tool is safe for development, staging, or example tokens, not for live production tokens with real user sessions."
    },
    {
      question: "What's the difference between HS256 and RS256 algorithms?",
      answer: "HS256 (HMAC SHA-256) is symmetric - same secret key signs and verifies tokens. If the secret leaks, anyone can create valid tokens. Use HS256 for single-server apps where the server both creates and validates tokens. RS256 (RSA SHA-256) is asymmetric - private key signs, public key verifies. Multiple services can verify tokens with the public key without accessing the private key. Use RS256 for distributed systems, microservices, or when multiple services verify tokens."
    },
    {
      question: "How do I check if a JWT is expired?",
      answer: "Look at the exp (expiration) claim in the decoded payload. It's a Unix timestamp (seconds since Jan 1, 1970). If exp is less than current time, the token is expired. This tool shows both the raw timestamp and human-readable date/time. Expired tokens should be rejected by APIs with 401 Unauthorized. To fix, refresh the token or re-authenticate the user. Typical token lifetimes: 15min (access), 7 days (refresh), 1hr (ID tokens)."
    },
    {
      question: "What are standard JWT claims (iss, sub, aud, exp)?",
      answer: "Standard claims follow IETF RFC 7519: iss (issuer) - who created the token, sub (subject) - user ID the token represents, aud (audience) - who the token is intended for, exp (expiration) - when token expires, iat (issued at) - when token was created, nbf (not before) - when token becomes valid, jti (JWT ID) - unique token identifier for revocation. These enable validation, revocation, and proper authentication flows. Custom claims (roles, permissions) are application-specific."
    },
    {
      question: "Can I store sensitive data in JWT payloads?",
      answer: "No! JWTs are Base64-encoded (readable by anyone), not encrypted. Anyone with access to the token can decode and read the payload using tools like this. Never store passwords, API keys, social security numbers, credit card data, or any confidential information in JWTs. Store only minimal data: user ID, roles, permissions. For sensitive data, store it server-side and use the JWT's sub (user ID) claim to look it up."
    },
    {
      question: "Why does my JWT start with 'eyJ'?",
      answer: "All JWTs start with 'eyJ' because it's the Base64 encoding of the JSON header's opening brace and quote: '{\"'. The header typically starts with {\"alg\":... which Base64-encodes to eyJhbGci... This is a quick way to identify JWT tokens visually. If your token doesn't start with 'eyJ', it's not a JWT - it might be an opaque token, session ID, or API key in a different format."
    },
    {
      question: "What does 'kid' in the header mean?",
      answer: "kid (key ID) identifies which cryptographic key was used to sign the token. Essential for key rotation - when you change signing keys, old tokens use old kid, new tokens use new kid. Validators use kid to fetch the correct public key for signature verification. OIDC providers (Auth0, Okta) expose JWKS (JSON Web Key Set) endpoints with multiple keys indexed by kid. Without kid, you can't rotate keys without invalidating all existing tokens."
    },
    {
      question: "Can I use this tool to create or modify JWTs?",
      answer: "No. This tool only decodes (reads) existing JWTs, it cannot create new tokens or modify existing ones. Creating valid JWTs requires the secret key (HS256) or private key (RS256) for signing. Use server-side libraries (jsonwebtoken for Node.js, PyJWT for Python) to create tokens. Modifying JWTs invalidates the signature - the modified token will fail verification. JWT immutability is a security feature."
    },
    {
      question: "How do I debug 401 Unauthorized errors with JWTs?",
      answer: "1) Copy the JWT from the Authorization header, 2) Decode it with this tool, 3) Check: exp is in the future (not expired), aud matches your API, iss matches your identity provider, required claims (sub, roles) are present, algorithm (alg) matches what your API expects (HS256 vs RS256). Common issues: expired tokens, wrong audience, missing claims, algorithm mismatch. If all claims look correct, the signature is likely invalid - verify the secret/public key matches between token creator and validator."
    }
  ],

  security: {
    title: "Security & Privacy",
    content: `Your JWT tokens never leave your browser. This decoder operates entirely client-side using JavaScript's atob() (Base64 decoding) function built into your web browser. There are no server uploads, no backend processing, and no data transmission to any external services.

### Privacy Guarantees

- **100% Client-Side Processing:** All JWT decoding happens in your browser's JavaScript engine. Tokens stay on your device.
- **No Server Uploads:** We don't have servers to process your JWTs. The tool works completely offline after first load.
- **No Data Storage:** Your tokens are not saved, logged, or stored anywhere. Refresh the page and they're gone (unless you save them locally).
- **No Analytics Tracking:** We don't track what you decode, how often you use the tool, or any token-specific data.
- **Transparent & Auditable:** Inspect browser DevTools Network tab - you'll see zero outbound requests containing your tokens.

This makes the tool safe for decoding development and staging tokens. For production tokens with real user sessions, use local tools or your own JWT decoder to ensure absolute security.

### CRITICAL: Security Limitations

**This tool does NOT verify JWT signatures.** It only decodes Base64-encoded sections. Anyone can create a JWT with fake claims. Never use client-side JWT decoding for authentication or authorization decisions in production.

**Always verify signatures on the server** using cryptographic libraries (jsonwebtoken, PyJWT, golang-jwt). Server-side validation with proper key management is the only secure way to authenticate JWTs.

**Never store JWTs in localStorage** (vulnerable to XSS). Prefer httpOnly, secure, SameSite cookies that JavaScript cannot access. Never expose JWTs in URLs or GET parameters (logged in server logs, browser history).

### Best Practices for JWT Security

1. Use strong algorithms: RS256, ES256 (asymmetric) for distributed systems
2. Short expiration: 15min-1hr for access tokens, use refresh tokens for longer sessions
3. Validate all claims: iss, aud, exp, nbf
4. Never store sensitive data in payloads (PII, credentials, secrets)
5. Implement token revocation using jti (JWT ID) blacklists or short expiration
6. Use httpOnly cookies for storage, not localStorage or sessionStorage
7. Rotate signing keys regularly, use kid (key ID) for key identification
8. Monitor for algorithm confusion attacks (downgrade to alg: "none")
9. Validate audience (aud) to prevent cross-service token reuse
10. Use secure key management (AWS KMS, HashiCorp Vault) for signing keys`
  },

  stats: {
    "Decode Speed": "<10ms",
    "Max Token Size": "100KB",
    "Signature Verify": "No",
    "Standards": "RFC 7519",
    "Server Uploads": "0"
  }
};
